// test_catalogue.cpp - offline harness for src\gen: the archive readers and the generator.
// Reads the game folder named by UNIQUETAB_TEST_GAME_DIR, writes only under build\test.
//
//   test_catalogue.exe --readers <dump.txt>      counts + a deterministic sample of decoded
//                                                records and text tags (diffed against
//                                                tools\dump_gen_sample.py's output)
//   test_catalogue.exe --catalogue <oracle.bin> [<out.bin>]
//                                                generates catalogue.bin from the game folder
//                                                and compares it byte for byte with the oracle
//                                                file; the generated bytes go to <out.bin>
//   test_catalogue.exe --pages <data dir> [<out dir>]
//                                                the three uniq txt files against data\uniq,
//                                                plus the capacity check on uniq-pages.arz
//   test_catalogue.exe --ensure <data dir> <mod dir>
//                                                the DLL's start-up path (gen::ensureOutputs)
//                                                against a scratch mod folder: first launch,
//                                                matching stamp, changed stamp, missing output,
//                                                the error paths
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>

#include "gen/arc_reader.h"
#include "gen/arz_reader.h"
#include "gen/catalogue_gen.h"
#include "gen/generate.h"
#include "gen/pages_gen.h"

#include <algorithm>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <map>
#include <string>
#include <vector>

namespace {

int fail(const char* what) {
    std::fprintf(stderr, "[test] FAIL: %s\n", what);
    return 1;
}

std::string gameDir() {
    const char* g = std::getenv("UNIQUETAB_TEST_GAME_DIR");
    return g ? g : "";
}

// The record as Python's arz.py sees it: the last field of a name wins, sorted by name.
void dumpRecord(FILE* out, const gen::ArzRecord& rec) {
    std::map<std::string, const gen::ArzField*> last;
    for (const gen::ArzField& f : rec.fields) last[f.name] = &f;
    for (const auto& kv : last) {
        const gen::ArzField& f = *kv.second;
        std::fprintf(out, "  %s\t%u\t", kv.first.c_str(), unsigned(f.type));
        for (std::size_t i = 0; i < f.raw.size(); ++i) {
            if (i) std::fputc(',', out);
            if (f.type == gen::kFtString) std::fputs(f.strs[i].c_str(), out);
            else if (f.type == gen::kFtFloat) std::fprintf(out, "%08x", f.raw[i]);
            else std::fprintf(out, "%d", int(f.raw[i]));
        }
        std::fputc('\n', out);
    }
}

int readers(const std::string& dumpPath) {
    std::string game = gameDir();
    if (game.empty()) return fail("UNIQUETAB_TEST_GAME_DIR is not set");
    auto t0 = std::chrono::steady_clock::now();
    gen::ArzDatabase db;
    std::string err;
    if (!db.loadGame(game, &err)) return fail(err.c_str());
    std::unordered_map<std::string, std::string> tags;
    if (!gen::loadTextTags(game, "EN", tags, &err)) return fail(err.c_str());
    gen::ArcSet items, ui;
    if (!items.load(game, "resources\\Items.arc", &err)) return fail(err.c_str());
    if (!ui.load(game, "resources\\UI.arc", &err)) return fail(err.c_str());
    auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
        std::chrono::steady_clock::now() - t0).count();

    FILE* out = std::fopen(dumpPath.c_str(), "wb");
    if (!out) return fail("cannot write the dump");
    for (const gen::ArzArchive& a : db.archives())
        std::fprintf(out, "arz\t%s\t%zu\t%zu\n", a.tag().c_str(), a.recordCount(), a.stringCount());
    std::fprintf(out, "merged\t%zu\n", db.size());
    std::fprintf(out, "tags\t%zu\n", tags.size());
    std::fprintf(out, "items.arc\t%zu\n", items.size());
    std::fprintf(out, "ui.arc\t%zu\n", ui.size());

    const auto& w = db.winners();
    std::size_t step = w.size() / 200;
    if (step == 0) step = 1;
    std::size_t decoded = 0;
    for (std::size_t i = 0; i < w.size() && decoded < 200; i += step, ++decoded) {
        const gen::ArzArchive& a = db.archives()[w[i].first];
        gen::ArzRecord rec;
        if (!a.decode(*w[i].second, rec)) { std::fclose(out); return fail("record decode"); }
        std::fprintf(out, "record\t%s\t%s\n", w[i].second->key.c_str(), a.tag().c_str());
        dumpRecord(out, rec);
    }
    std::vector<std::string> keys;
    keys.reserve(tags.size());
    for (const auto& kv : tags) keys.push_back(kv.first);
    std::sort(keys.begin(), keys.end());
    std::size_t tstep = keys.size() / 200;
    if (tstep == 0) tstep = 1;
    for (std::size_t i = 0; i < keys.size(); i += tstep)
        std::fprintf(out, "tag\t%s=%s\n", keys[i].c_str(), tags[keys[i]].c_str());
    std::fclose(out);

    // Every record of every archive decodes: the LZ4 decoder against the whole database.
    std::size_t total = 0;
    gen::ArzRecord rec;
    for (const gen::ArzArchive& a : db.archives())
        for (const gen::ArzEntry& e : a.entries()) {
            if (!a.decode(e, rec)) {
                std::fprintf(stderr, "[test] decode failed: %s %s\n", a.tag().c_str(), e.name.c_str());
                return 1;
            }
            ++total;
        }
    auto ms2 = std::chrono::duration_cast<std::chrono::milliseconds>(
        std::chrono::steady_clock::now() - t0).count();
    std::printf("[test] readers: %zu merged records, %zu tags, %zu Items.arc, %zu UI.arc entries;"
                " load %lld ms, all %zu records decoded in %lld ms\n",
                db.size(), tags.size(), items.size(), ui.size(), (long long)ms, total, (long long)ms2);
    return 0;
}

bool readAll(const std::string& path, std::vector<std::uint8_t>& out) {
    FILE* f = std::fopen(path.c_str(), "rb");
    if (!f) return false;
    std::fseek(f, 0, SEEK_END);
    long n = std::ftell(f);
    std::fseek(f, 0, SEEK_SET);
    out.resize(n > 0 ? std::size_t(n) : 0);
    bool ok = out.empty() || std::fread(out.data(), 1, out.size(), f) == out.size();
    std::fclose(f);
    return ok;
}

// Prints the first differing offset with 16 bytes of context on both sides.
int compareBytes(const char* what, const std::vector<std::uint8_t>& got,
                 const std::vector<std::uint8_t>& want) {
    std::size_t n = std::min(got.size(), want.size()), at = n;
    for (std::size_t i = 0; i < n; ++i) if (got[i] != want[i]) { at = i; break; }
    if (at == n && got.size() == want.size()) {
        std::printf("[test] %s: byte-identical (%zu B)\n", what, got.size());
        return 0;
    }
    std::printf("[test] FAIL: %s differs at offset %zu (generated %zu B, oracle %zu B)\n",
                what, at, got.size(), want.size());
    std::size_t from = at >= 16 ? at - 16 : 0;
    for (int side = 0; side < 2; ++side) {
        const auto& v = side ? want : got;
        std::printf("  %s:", side ? "oracle   " : "generated");
        for (std::size_t i = from; i < from + 48 && i < v.size(); ++i) std::printf(" %02x", v[i]);
        std::printf("\n            ");
        for (std::size_t i = from; i < from + 48 && i < v.size(); ++i)
            std::printf(" %c ", v[i] >= 32 && v[i] < 127 ? char(v[i]) : '.');
        std::printf("\n");
    }
    return 1;
}

int catalogue(const std::string& oracle, const std::string& outPath) {
    std::string game = gameDir();
    if (game.empty()) return fail("UNIQUETAB_TEST_GAME_DIR is not set");
    auto t0 = std::chrono::steady_clock::now();
    gen::GameData g;
    std::string err;
    if (!g.load(game, "EN", &err)) return fail(err.c_str());
    std::vector<gen::CatalogueItem> items;
    std::vector<std::string> warnings;
    if (!gen::collectItems(g, items, warnings, &err)) return fail(err.c_str());
    std::vector<std::uint8_t> bin;
    gen::CatalogueStats st;
    if (!gen::packCatalogue(items, bin, &st, &err)) return fail(err.c_str());
    auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
        std::chrono::steady_clock::now() - t0).count();
    std::printf("[test] catalogue: %zu items (%zu equipment, %zu relics %zu/%zu/%zu Rare/Epic/Legendary,"
                " %zu curated, %zu default visible), %zu sets / %zu members, %zu strings %zu B,"
                " %zu B total, generated in %lld ms\n",
                st.items, st.equipment, st.relics, st.relicsRare, st.relicsEpic, st.relicsLegendary,
                st.extras, st.defaultVisible, st.sets, st.members, st.strings, st.stringBytes,
                st.bytes, (long long)ms);
    for (const std::string& w : warnings) std::printf("[test] warning: %s\n", w.c_str());
    if (!outPath.empty()) {
        FILE* f = std::fopen(outPath.c_str(), "wb");
        if (f) { std::fwrite(bin.data(), 1, bin.size(), f); std::fclose(f); }
    }
    std::vector<std::uint8_t> want;
    if (!readAll(oracle, want)) return fail("cannot read the oracle catalogue.bin");
    return compareBytes("catalogue.bin", bin, want);
}

int pages(const std::string& dataDir, const std::string& outDir) {
    std::string game = gameDir();
    if (game.empty()) return fail("UNIQUETAB_TEST_GAME_DIR is not set");
    auto t0 = std::chrono::steady_clock::now();
    gen::GameData g;
    std::string err;
    if (!g.load(game, "EN", &err)) return fail(err.c_str());
    std::vector<gen::CatalogueItem> items;
    std::vector<std::string> warnings;
    if (!gen::collectItems(g, items, warnings, &err)) return fail(err.c_str());
    gen::PagesOutput po;
    if (!gen::generatePages(g, items, po, &err)) return fail(err.c_str());
    auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
        std::chrono::steady_clock::now() - t0).count();
    std::printf("[test] pages: %zu records on %zu pages in %zu groups (%zu skipped), generated in %lld ms\n",
                po.itemCount, po.pageCount, po.groupList.size(), po.skipped, (long long)ms);
    for (const auto& gr : po.groupList)
        std::printf("[test]   %-10s %4zu boxes on %2zu pages\n", gr.label.c_str(), gr.entries, gr.pages);
    int rc = 0;
    if (!gen::checkPageCapacity(dataDir + "\\uniq\\uniq-pages.arz", po, &err)) {
        std::printf("[test] FAIL: capacity: %s\n", err.c_str());
        rc = 1;
    } else {
        std::printf("[test] capacity: every box the layout names exists in uniq-pages.arz\n");
    }
    const char* names[3] = {"uniq-records.txt", "uniq-pages.txt", "uniq-groups.txt"};
    const std::string* texts[3] = {&po.records, &po.pages, &po.groups};
    for (int i = 0; i < 3; ++i) {
        std::vector<std::uint8_t> got(texts[i]->begin(), texts[i]->end()), want;
        if (!outDir.empty()) {
            FILE* f = std::fopen((outDir + "\\" + names[i]).c_str(), "wb");
            if (f) { std::fwrite(got.data(), 1, got.size(), f); std::fclose(f); }
        }
        if (!readAll(dataDir + "\\oracle\\" + names[i], want)) return fail("cannot read the oracle txt");
        if (compareBytes(names[i], got, want)) rc = 1;
    }
    return rc;
}

// The stamp + rename path the DLL runs at start-up, against a scratch mod folder: a first launch
// (nothing there), a second launch (the stamp matches, nothing is touched), a changed stamp, a
// deleted output, and a game folder without archives (an error that leaves the files alone).
unsigned long long mtimeOf(const std::string& p) {
    WIN32_FILE_ATTRIBUTE_DATA fa;
    if (!GetFileAttributesExA(p.c_str(), GetFileExInfoStandard, &fa)) return 0;
    return (unsigned long long(fa.ftLastWriteTime.dwHighDateTime) << 32) | fa.ftLastWriteTime.dwLowDateTime;
}

int ensure(const std::string& dataDir, const std::string& modDir) {
    std::string game = gameDir();
    if (game.empty()) return fail("UNIQUETAB_TEST_GAME_DIR is not set");
    const char* names[4] = {"catalogue.bin", "uniq-records.txt", "uniq-pages.txt", "uniq-groups.txt"};
    const std::string oracle[4] = {dataDir + "\\oracle\\catalogue.bin", dataDir + "\\oracle\\uniq-records.txt",
                                   dataDir + "\\oracle\\uniq-pages.txt", dataDir + "\\oracle\\uniq-groups.txt"};
    const std::string pagesArz = dataDir + "\\uniq\\uniq-pages.arz";
    const std::string stamp = modDir + "\\catalogue.stamp";
    for (const char* n : names) DeleteFileA((modDir + "\\" + n).c_str());
    DeleteFileA(stamp.c_str());
    int rc = 0;
    auto check = [&](bool ok, const char* what) {
        std::printf("[test] %s: %s\n", ok ? "ok  " : "FAIL", what);
        if (!ok) rc = 1;
    };
    auto noTemporaries = [&]() {
        for (const char* n : names)
            if (GetFileAttributesA((modDir + "\\" + n + ".tmp").c_str()) != INVALID_FILE_ATTRIBUTES) return false;
        return true;
    };
    gen::GenReport r;

    // a: first launch
    auto t0 = std::chrono::steady_clock::now();
    bool ok = gen::ensureOutputsGuarded(game, modDir, pagesArz, "EN", r);
    auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - t0).count();
    std::printf("[test] ensure (first launch): %s, reason \"%s\", %lld ms wall - %s%s\n",
                ok ? "generated" : "FAILED", r.reason.c_str(), (long long)ms, r.summary.c_str(), r.error.c_str());
    check(ok && r.generated && r.reason == "catalogue.bin is missing", "a first launch generates, reason = the missing catalogue");
    for (int i = 0; i < 4; ++i) {
        std::vector<std::uint8_t> got, want;
        if (!readAll(modDir + "\\" + names[i], got) || !readAll(oracle[i], want)) { check(false, names[i]); continue; }
        if (compareBytes(names[i], got, want)) rc = 1;
    }
    check(GetFileAttributesA(stamp.c_str()) != INVALID_FILE_ATTRIBUTES, "catalogue.stamp written");
    check(noTemporaries(), "no .tmp left behind");
    unsigned long long mt[4];
    for (int i = 0; i < 4; ++i) mt[i] = mtimeOf(modDir + "\\" + names[i]);

    // b: second launch - the stamp matches
    t0 = std::chrono::steady_clock::now();
    ok = gen::ensureOutputsGuarded(game, modDir, pagesArz, "EN", r);
    ms = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - t0).count();
    std::printf("[test] ensure (second launch): upToDate=%d in %lld ms\n", int(r.upToDate), (long long)ms);
    check(ok && r.upToDate && !r.generated, "a matching stamp does nothing");
    bool untouched = true;
    for (int i = 0; i < 4; ++i) untouched = untouched && mtimeOf(modDir + "\\" + names[i]) == mt[i];
    check(untouched, "the four files were not rewritten");

    // c: a stamp that differs (a game update)
    { FILE* f = std::fopen(stamp.c_str(), "wb"); if (f) { std::fputs("GDUT-STAMP 1\nlang=EN\nold\n", f); std::fclose(f); } }
    ok = gen::ensureOutputsGuarded(game, modDir, pagesArz, "EN", r);
    check(ok && r.generated && r.reason.find("does not match") != std::string::npos, "a changed stamp regenerates");

    // d: one output missing
    DeleteFileA((modDir + "\\uniq-groups.txt").c_str());
    ok = gen::ensureOutputsGuarded(game, modDir, pagesArz, "EN", r);
    check(ok && r.generated && r.reason == "uniq-groups.txt is missing", "a missing output regenerates");
    for (int i = 0; i < 4; ++i) mt[i] = mtimeOf(modDir + "\\" + names[i]);
    std::vector<std::uint8_t> stampBefore;
    readAll(stamp, stampBefore);

    // e: a game folder without archives - the error path keeps everything
    ok = gen::ensureOutputsGuarded(modDir, modDir, pagesArz, "EN", r);
    std::printf("[test] ensure (no archives): %s\n", r.error.c_str());
    check(!ok && !r.generated && !r.error.empty(), "a game folder without archives is an error");
    untouched = true;
    for (int i = 0; i < 4; ++i) untouched = untouched && mtimeOf(modDir + "\\" + names[i]) == mt[i];
    std::vector<std::uint8_t> stampAfter;
    readAll(stamp, stampAfter);
    check(untouched && stampAfter == stampBefore, "the files and the stamp are kept on failure");
    check(noTemporaries(), "no .tmp left behind by the failure");

    // f: a page archive that is not there - refused before anything is written
    DeleteFileA(stamp.c_str());
    ok = gen::ensureOutputsGuarded(game, modDir, modDir + "\\no-such.arz", "EN", r);
    check(!ok && r.error.find("capacity") != std::string::npos, "a missing uniq-pages.arz is refused");
    untouched = true;
    for (int i = 0; i < 4; ++i) untouched = untouched && mtimeOf(modDir + "\\" + names[i]) == mt[i];
    check(untouched && noTemporaries(), "the files are kept, no .tmp");
    return rc;
}

} // namespace

int main(int argc, char** argv) {
    if (argc >= 4 && std::string(argv[1]) == "--ensure") return ensure(argv[2], argv[3]);
    if (argc >= 3 && std::string(argv[1]) == "--readers") return readers(argv[2]);
    if (argc >= 3 && std::string(argv[1]) == "--pages") return pages(argv[2], argc >= 4 ? argv[3] : "");
    if (argc >= 3 && std::string(argv[1]) == "--catalogue")
        return catalogue(argv[2], argc >= 4 ? argv[3] : "");
    std::fprintf(stderr, "usage: test_catalogue --readers <dump.txt> | --catalogue <oracle.bin> [<out.bin>] | "
                         "--pages <data dir> [<out dir>] | --ensure <data dir> <mod dir>\n");
    return 2;
}
