// gd_exports.h - generated by tools/gen_exports_header.py. DO NOT EDIT BY HAND.
//
// Grim Dawn 1.3.0.8 x64 (build 24825149).
// Exported symbol names copied verbatim from tools/exports/{Engine,Game}-x64-exports.txt;
// the comment above each macro is undname.exe output for that exact string.
//
// Usage:
//     HMODULE hEngine = GetModuleHandleA("Engine.dll");
//     HMODULE hGame    = GetModuleHandleA("Game.dll");
//     auto SetTransferOpen = reinterpret_cast<GD_GameEngine_SetTransferOpen_t>(
//         GetProcAddress(hGame, GD_GAMEENGINE_SETTRANSFEROPEN));
//
// Calling convention: every method here is a non-static member function compiled for the
// Microsoft x64 ABI, so the typedefs below take the object pointer as the first argument and
// are declared __cdecl (on x64 __cdecl/__thiscall/__stdcall all collapse to the same ABI).
// A member returning a class BY VALUE (Rect, Vec2, std::string, ...) also takes a hidden
// pointer to the return slot as the SECOND argument, before the declared ones. Those are
// marked "sret" in the notes; the typedefs in this header cover only the simple cases.
//
// Read-only rule for milestones M1-M4: names that create, move, delete or persist items are
// still listed (they are part of the class) but are marked WRITE - do not call them.

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

// ---------------------------------------------------------------------------------------------
// ItemClassification
// ---------------------------------------------------------------------------------------------
// GAME::ItemClassification appears in the exported signatures of
// GameEngine::GetItemColor, GameEngine::GetItemBackground and Item::GetItemClassification
// (mangled as W4ItemClassification@2@). The *names* are known from the database records
// (records/game/gameengine.dbr has ItemNameCommon / ItemNameMagical / ItemNameRare /
// ItemNameEpic / ItemNameLegendary / ItemNameQuest / ItemNameBroken / ItemNameArtifact /
// ItemNameArtifactFormula / ItemNameEnchantment / ItemNameLore / ItemNamePotion styles, and
// itemClassification values in item records are the strings Common, Magical, Rare, Epic,
// Legendary, Quest, Broken).
//
// *** THE NUMERIC ORDER IS UNVERIFIED. *** Nothing exported reveals it. Do not hard-code these
// values; at runtime, call GameEngine::GetItemClassificationName(c) for c = 0..N and read the
// returned tag, or compare Item::GetItemClassification() against a known item.
//
// Plausible (record-file order, NOT confirmed):
//   0 Common, 1 Magical, 2 Rare, 3 Epic, 4 Legendary, 5 Quest, 6 Broken
enum GD_ItemClassification_Unverified {
    GD_ITEMCLASS_UNKNOWN = -1
};


// ---------------------------------------------------------------------------------------------
// Engine singleton and per-frame hooks   [Engine.dll]
// ---------------------------------------------------------------------------------------------
// public: class GAME::DatabaseArchive * __ptr64 __cdecl GAME::Engine::GetDatabaseArchive(void) __ptr64
#define GD_ENGINE_GETDATABASEARCHIVE "?GetDatabaseArchive@Engine@GAME@@QEAAPEAVDatabaseArchive@2@XZ"
// public: class GAME::FilterFunction<class GAME::Entity> * __ptr64 __cdecl GAME::Engine::GetEntityRenderFilter(void) __ptr64
#define GD_ENGINE_GETENTITYRENDERFILTER "?GetEntityRenderFilter@Engine@GAME@@QEAAPEAV?$FilterFunction@VEntity@GAME@@@2@XZ"
// public: unsigned int __cdecl GAME::Engine::GetFrameCount(void)const __ptr64
#define GD_ENGINE_GETFRAMECOUNT "?GetFrameCount@Engine@GAME@@QEBAIXZ"
// public: class GAME::GameInfo * __ptr64 __cdecl GAME::Engine::GetGameInfo(void) __ptr64
#define GD_ENGINE_GETGAMEINFO "?GetGameInfo@Engine@GAME@@QEAAPEAVGameInfo@2@XZ"
// public: class GAME::GraphicsEngine * __ptr64 __cdecl GAME::Engine::GetGraphicsEngine(void)const __ptr64
#define GD_ENGINE_GETGRAPHICSENGINE "?GetGraphicsEngine@Engine@GAME@@QEBAPEAVGraphicsEngine@2@XZ"
// public: bool __cdecl GAME::Engine::HasLoadedCustomDatabase(void)const __ptr64
#define GD_ENGINE_HASLOADEDCUSTOMDATABASE "?HasLoadedCustomDatabase@Engine@GAME@@QEBA_NXZ"
// public: void __cdecl GAME::Engine::PresentSurface(void) __ptr64
#define GD_ENGINE_PRESENTSURFACE "?PresentSurface@Engine@GAME@@QEAAXXZ"
// class GAME::Engine * __ptr64 __ptr64 GAME::gEngine
#define GD_ENGINE_GENGINE "?gEngine@GAME@@3PEAVEngine@1@EA"

// ---------------------------------------------------------------------------------------------
// GraphicsEngine   [Engine.dll]
// ---------------------------------------------------------------------------------------------
// public: class GAME::GraphicsCanvas & __ptr64 __cdecl GAME::GraphicsEngine::GetCanvas(void) __ptr64
#define GD_GFXENGINE_GETCANVAS "?GetCanvas@GraphicsEngine@GAME@@QEAAAEAVGraphicsCanvas@2@XZ"
// public: class GAME::GraphicsFont2 const * __ptr64 __cdecl GAME::GraphicsEngine::LoadFont(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64) __ptr64
#define GD_GFXENGINE_LOADFONT "?LoadFont@GraphicsEngine@GAME@@QEAAPEBVGraphicsFont2@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z"
// public: class GAME::GraphicsTexture const * __ptr64 __cdecl GAME::GraphicsEngine::LoadTexture(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64) __ptr64
#define GD_GFXENGINE_LOADTEXTURE "?LoadTexture@GraphicsEngine@GAME@@QEAAPEBVGraphicsTexture@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z"
// public: void __cdecl GAME::GraphicsEngine::PresentSurface(void) __ptr64
#define GD_GFXENGINE_PRESENTSURFACE "?PresentSurface@GraphicsEngine@GAME@@QEAAXXZ"
// public: void __cdecl GAME::GraphicsEngine::UnloadFont(class GAME::GraphicsFont2 const * __ptr64) __ptr64
#define GD_GFXENGINE_UNLOADFONT "?UnloadFont@GraphicsEngine@GAME@@QEAAXPEBVGraphicsFont2@2@@Z"
// public: void __cdecl GAME::GraphicsEngine::UnloadTexture(class GAME::GraphicsTexture const * __ptr64) __ptr64
#define GD_GFXENGINE_UNLOADTEXTURE "?UnloadTexture@GraphicsEngine@GAME@@QEAAXPEBVGraphicsTexture@2@@Z"

// ---------------------------------------------------------------------------------------------
// GraphicsCanvas - frame, size, viewport, clipping   [Engine.dll]
// ---------------------------------------------------------------------------------------------
// public: bool __cdecl GAME::GraphicsCanvas::BeginFrame(void) __ptr64
#define GD_CANVAS_BEGINFRAME "?BeginFrame@GraphicsCanvas@GAME@@QEAA_NXZ"
// public: void __cdecl GAME::GraphicsCanvas::ClearClippingRect(void) __ptr64
#define GD_CANVAS_CLEARCLIPPINGRECT "?ClearClippingRect@GraphicsCanvas@GAME@@QEAAXXZ"
// public: void __cdecl GAME::GraphicsCanvas::EndFrame(void) __ptr64
#define GD_CANVAS_ENDFRAME "?EndFrame@GraphicsCanvas@GAME@@QEAAXXZ"
// public: class GAME::Rect const & __ptr64 __cdecl GAME::GraphicsCanvas::GetClippingRect(void) __ptr64
#define GD_CANVAS_GETCLIPPINGRECT "?GetClippingRect@GraphicsCanvas@GAME@@QEAAAEBVRect@2@XZ"
// public: int __cdecl GAME::GraphicsCanvas::GetHeight(void)const __ptr64
#define GD_CANVAS_GETHEIGHT "?GetHeight@GraphicsCanvas@GAME@@QEBAHXZ"
// public: class GAME::Viewport const & __ptr64 __cdecl GAME::GraphicsCanvas::GetViewport(void)const __ptr64
#define GD_CANVAS_GETVIEWPORT "?GetViewport@GraphicsCanvas@GAME@@QEBAAEBVViewport@2@XZ"
// public: int __cdecl GAME::GraphicsCanvas::GetWidth(void)const __ptr64
#define GD_CANVAS_GETWIDTH "?GetWidth@GraphicsCanvas@GAME@@QEBAHXZ"
// public: void __cdecl GAME::GraphicsCanvas::SetClippingRect(class GAME::Rect const & __ptr64,bool) __ptr64
#define GD_CANVAS_SETCLIPPINGRECT "?SetClippingRect@GraphicsCanvas@GAME@@QEAAXAEBVRect@2@_N@Z"
// public: void __cdecl GAME::GraphicsCanvas::SetDefaultState(void) __ptr64
#define GD_CANVAS_SETDEFAULTSTATE "?SetDefaultState@GraphicsCanvas@GAME@@QEAAXXZ"
// public: void __cdecl GAME::GraphicsCanvas::SetViewport(class GAME::Viewport const & __ptr64) __ptr64
#define GD_CANVAS_SETVIEWPORT "?SetViewport@GraphicsCanvas@GAME@@QEAAXAEBVViewport@2@@Z"

// ---------------------------------------------------------------------------------------------
// GraphicsCanvas - 2D drawing   [Engine.dll]
// ---------------------------------------------------------------------------------------------
// public: void __cdecl GAME::GraphicsCanvas::DrawDynamicRect(class GAME::Rect const & __ptr64,class GAME::Rect const & __ptr64,class GAME::Color const & __ptr64,float) __ptr64
#define GD_CANVAS_DRAWDYNAMICRECT "?DrawDynamicRect@GraphicsCanvas@GAME@@QEAAXAEBVRect@2@0AEBVColor@2@M@Z"
// public: void __cdecl GAME::GraphicsCanvas::DrawDynamicRect(class GAME::Rect const & __ptr64,class GAME::Color const & __ptr64,class GAME::Color const & __ptr64,float) __ptr64
#define GD_CANVAS_DRAWDYNAMICRECT_2 "?DrawDynamicRect@GraphicsCanvas@GAME@@QEAAXAEBVRect@2@AEBVColor@2@1M@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderHorizontalGradient(class GAME::Rect const & __ptr64,class GAME::Color const & __ptr64,class GAME::Color const & __ptr64) __ptr64
#define GD_CANVAS_RENDERHORIZONTALGRADIENT "?RenderHorizontalGradient@GraphicsCanvas@GAME@@QEAAXAEBVRect@2@AEBVColor@2@1@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderLine(class GAME::Vec2 const & __ptr64,class GAME::Vec2 const & __ptr64,class GAME::Color const & __ptr64) __ptr64
#define GD_CANVAS_RENDERLINE "?RenderLine@GraphicsCanvas@GAME@@QEAAXAEBVVec2@2@0AEBVColor@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderRect(class GAME::Rect const & __ptr64,class GAME::Rect const & __ptr64,class GAME::RenderTexture const * __ptr64,class GAME::Color const & __ptr64) __ptr64
#define GD_CANVAS_RENDERRECT "?RenderRect@GraphicsCanvas@GAME@@QEAAXAEBVRect@2@0PEBVRenderTexture@2@AEBVColor@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderRect(class GAME::Rect const & __ptr64,class GAME::Color const & __ptr64) __ptr64
#define GD_CANVAS_RENDERRECT_2 "?RenderRect@GraphicsCanvas@GAME@@QEAAXAEBVRect@2@AEBVColor@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderShadedRect(class GAME::Rect const & __ptr64,class GAME::Rect const & __ptr64,class GAME::RenderTexture const * __ptr64,class GAME::GraphicsShader2 const * __ptr64,class GAME::Name const & __ptr64,class GAME::Color const & __ptr64,float) __ptr64
#define GD_CANVAS_RENDERSHADEDRECT "?RenderShadedRect@GraphicsCanvas@GAME@@QEAAXAEBVRect@2@0PEBVRenderTexture@2@PEBVGraphicsShader2@2@AEBVName@2@AEBVColor@2@M@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderStyledRect(class GAME::Rect const & __ptr64,class GAME::Rect const & __ptr64,class GAME::RenderTexture const * __ptr64,class GAME::Name const & __ptr64,class GAME::Color const & __ptr64,float) __ptr64
#define GD_CANVAS_RENDERSTYLEDRECT "?RenderStyledRect@GraphicsCanvas@GAME@@QEAAXAEBVRect@2@0PEBVRenderTexture@2@AEBVName@2@AEBVColor@2@M@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderStyledRect(class GAME::Rect const & __ptr64,class GAME::Name const & __ptr64,class GAME::Color const & __ptr64) __ptr64
#define GD_CANVAS_RENDERSTYLEDRECT_2 "?RenderStyledRect@GraphicsCanvas@GAME@@QEAAXAEBVRect@2@AEBVName@2@AEBVColor@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderTriFan(class mem::vector<class GAME::Vec2> const & __ptr64,class GAME::Color const & __ptr64) __ptr64
#define GD_CANVAS_RENDERTRIFAN "?RenderTriFan@GraphicsCanvas@GAME@@QEAAXAEBV?$vector@VVec2@GAME@@@mem@@AEBVColor@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderVerticalGradient(class GAME::Rect const & __ptr64,class GAME::Color const & __ptr64,class GAME::Color const & __ptr64,bool) __ptr64
#define GD_CANVAS_RENDERVERTICALGRADIENT "?RenderVerticalGradient@GraphicsCanvas@GAME@@QEAAXAEBVRect@2@AEBVColor@2@1_N@Z"

// ---------------------------------------------------------------------------------------------
// GraphicsCanvas - text   [Engine.dll]
// ---------------------------------------------------------------------------------------------
// public: class GAME::Rect __cdecl GAME::GraphicsCanvas::CalcTextRect(class GAME::Rect,int,int,enum GAME::GraphicsXAlign,enum GAME::GraphicsYAlign)const __ptr64  [returns by value -> hidden sret pointer as arg 2]
#define GD_CANVAS_CALCTEXTRECT "?CalcTextRect@GraphicsCanvas@GAME@@QEBA?AVRect@2@V32@HHW4GraphicsXAlign@2@W4GraphicsYAlign@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderColoredText2d(int,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,class GAME::Color const & __ptr64,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERCOLOREDTEXT2D "?RenderColoredText2d@GraphicsCanvas@GAME@@QEAAXHHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEBVColor@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderColoredText2d(int,int,class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > const & __ptr64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,class GAME::Color const & __ptr64,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERCOLOREDTEXT2D_2 "?RenderColoredText2d@GraphicsCanvas@GAME@@QEAAXHHAEBV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@AEBVColor@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderColoredText2d(int,int,char const * __ptr64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,class GAME::Color const & __ptr64,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERCOLOREDTEXT2D_3 "?RenderColoredText2d@GraphicsCanvas@GAME@@QEAAXHHPEBDAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVColor@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(int,int,class GAME::Color const & __ptr64,class GAME::Color const & __ptr64,char const * __ptr64,class GAME::GraphicsFont2 const * __ptr64,int,enum GAME::GraphicsXAlign,enum GAME::GraphicsYAlign,enum GAME::FontStyleFlag,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERTEXT2D "?RenderText2d@GraphicsCanvas@GAME@@QEAAXHHAEBVColor@2@0PEBDPEBVGraphicsFont2@2@HW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontStyleFlag@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(int,int,class GAME::Color const & __ptr64,class GAME::Color const & __ptr64,unsigned short const * __ptr64,class GAME::GraphicsFont2 const * __ptr64,int,enum GAME::GraphicsXAlign,enum GAME::GraphicsYAlign,enum GAME::FontStyleFlag,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERTEXT2D_2 "?RenderText2d@GraphicsCanvas@GAME@@QEAAXHHAEBVColor@2@0PEBGPEBVGraphicsFont2@2@HW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontStyleFlag@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(int,int,class GAME::Color const & __ptr64,char const * __ptr64,class GAME::GraphicsFont2 const * __ptr64,int,enum GAME::GraphicsXAlign,enum GAME::GraphicsYAlign,enum GAME::FontStyleFlag,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERTEXT2D_3 "?RenderText2d@GraphicsCanvas@GAME@@QEAAXHHAEBVColor@2@PEBDPEBVGraphicsFont2@2@HW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontStyleFlag@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(int,int,class GAME::Color const & __ptr64,unsigned short const * __ptr64,class GAME::GraphicsFont2 const * __ptr64,int,enum GAME::GraphicsXAlign,enum GAME::GraphicsYAlign,enum GAME::FontStyleFlag,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERTEXT2D_4 "?RenderText2d@GraphicsCanvas@GAME@@QEAAXHHAEBVColor@2@PEBGPEBVGraphicsFont2@2@HW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontStyleFlag@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(int,int,char const * __ptr64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,float,enum GAME::GraphicsXAlign,enum GAME::GraphicsYAlign,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERTEXT2D_5 "?RenderText2d@GraphicsCanvas@GAME@@QEAAXHHPEBDAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(int,int,unsigned short const * __ptr64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,float,float,enum GAME::GraphicsXAlign,enum GAME::GraphicsYAlign,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERTEXT2D_6 "?RenderText2d@GraphicsCanvas@GAME@@QEAAXHHPEBGAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(int,int,unsigned short const * __ptr64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,float,enum GAME::GraphicsXAlign,enum GAME::GraphicsYAlign,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERTEXT2D_7 "?RenderText2d@GraphicsCanvas@GAME@@QEAAXHHPEBGAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(class GAME::Rect,class GAME::Color const & __ptr64,class GAME::Color const & __ptr64,char const * __ptr64,class GAME::GraphicsFont2 const * __ptr64,int,enum GAME::GraphicsXAlign,enum GAME::GraphicsYAlign,enum GAME::FontStyleFlag,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERTEXT2D_8 "?RenderText2d@GraphicsCanvas@GAME@@QEAAXVRect@2@AEBVColor@2@1PEBDPEBVGraphicsFont2@2@HW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontStyleFlag@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(class GAME::Rect,class GAME::Color const & __ptr64,class GAME::Color const & __ptr64,unsigned short const * __ptr64,class GAME::GraphicsFont2 const * __ptr64,int,enum GAME::GraphicsXAlign,enum GAME::GraphicsYAlign,enum GAME::FontStyleFlag,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERTEXT2D_9 "?RenderText2d@GraphicsCanvas@GAME@@QEAAXVRect@2@AEBVColor@2@1PEBGPEBVGraphicsFont2@2@HW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontStyleFlag@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(class GAME::Rect,class GAME::Color const & __ptr64,char const * __ptr64,class GAME::GraphicsFont2 const * __ptr64,int,enum GAME::GraphicsXAlign,enum GAME::GraphicsYAlign,enum GAME::FontStyleFlag,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERTEXT2D_10 "?RenderText2d@GraphicsCanvas@GAME@@QEAAXVRect@2@AEBVColor@2@PEBDPEBVGraphicsFont2@2@HW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontStyleFlag@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(class GAME::Rect,class GAME::Color const & __ptr64,unsigned short const * __ptr64,class GAME::GraphicsFont2 const * __ptr64,int,enum GAME::GraphicsXAlign,enum GAME::GraphicsYAlign,enum GAME::FontStyleFlag,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERTEXT2D_11 "?RenderText2d@GraphicsCanvas@GAME@@QEAAXVRect@2@AEBVColor@2@PEBGPEBVGraphicsFont2@2@HW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontStyleFlag@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(class GAME::Rect,unsigned short const * __ptr64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,float,enum GAME::GraphicsXAlign,enum GAME::GraphicsYAlign,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERTEXT2D_12 "?RenderText2d@GraphicsCanvas@GAME@@QEAAXVRect@2@PEBGAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderText2dBox(int,int,class GAME::Color const & __ptr64,char const * __ptr64,class GAME::GraphicsFont2 const * __ptr64,int,bool,class GAME::Color const * __ptr64,enum GAME::FontStyleFlag,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERTEXT2DBOX "?RenderText2dBox@GraphicsCanvas@GAME@@QEAAXHHAEBVColor@2@PEBDPEBVGraphicsFont2@2@H_NPEBV32@W4FontStyleFlag@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderText2dBox(int,int,class GAME::Color const & __ptr64,unsigned short const * __ptr64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,float,bool,class GAME::Color const * __ptr64) __ptr64
#define GD_CANVAS_RENDERTEXT2DBOX_2 "?RenderText2dBox@GraphicsCanvas@GAME@@QEAAXHHAEBVColor@2@PEBGAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M_NPEBV32@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderText2dBox(int,int,class GAME::Color const & __ptr64,unsigned short const * __ptr64,class GAME::GraphicsFont2 const * __ptr64,int,bool,class GAME::Color const * __ptr64,enum GAME::FontStyleFlag,enum GAME::FontLayout) __ptr64
#define GD_CANVAS_RENDERTEXT2DBOX_3 "?RenderText2dBox@GraphicsCanvas@GAME@@QEAAXHHAEBVColor@2@PEBGPEBVGraphicsFont2@2@H_NPEBV32@W4FontStyleFlag@2@W4FontLayout@2@@Z"
// public: void __cdecl GAME::GraphicsCanvas::RenderText2dParagraph(int,int,class GAME::Color const & __ptr64,class GAME::Color const & __ptr64,class mem::vector<class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > > const & __ptr64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,bool) __ptr64
#define GD_CANVAS_RENDERTEXT2DPARAGRAPH "?RenderText2dParagraph@GraphicsCanvas@GAME@@QEAAXHHAEBVColor@2@0AEBV?$vector@V?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@mem@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z"

// ---------------------------------------------------------------------------------------------
// GraphicsTexture / GraphicsFont2   [Engine.dll]
// ---------------------------------------------------------------------------------------------
// public: int __cdecl GAME::GraphicsTexture::GetHeight(void)const __ptr64
#define GD_TEXTURE_GETHEIGHT "?GetHeight@GraphicsTexture@GAME@@QEBAHXZ"
// public: unsigned int __cdecl GAME::GraphicsFont2::GetLineHeight(unsigned int,enum GAME::FontStyleFlag)const __ptr64
#define GD_TEXTURE_GETLINEHEIGHT "?GetLineHeight@GraphicsFont2@GAME@@QEBAIIW4FontStyleFlag@2@@Z"
// public: class GAME::RenderTexture const * __ptr64 __cdecl GAME::GraphicsTexture::GetTexture(int)const __ptr64
#define GD_TEXTURE_GETTEXTURE "?GetTexture@GraphicsTexture@GAME@@QEBAPEBVRenderTexture@2@H@Z"
// public: class GAME::RenderTexture const * __ptr64 __cdecl GAME::GraphicsTexture::GetTexture(void)const __ptr64
#define GD_TEXTURE_GETTEXTURE_2 "?GetTexture@GraphicsTexture@GAME@@QEBAPEBVRenderTexture@2@XZ"
// public: int __cdecl GAME::GraphicsTexture::GetWidth(void)const __ptr64
#define GD_TEXTURE_GETWIDTH "?GetWidth@GraphicsTexture@GAME@@QEBAHXZ"

// ---------------------------------------------------------------------------------------------
// Free 2D primitive helpers   [Engine.dll]
// ---------------------------------------------------------------------------------------------
// public: __cdecl GAME::GraphicsPrimitiveDrawer::GraphicsPrimitiveDrawer(class GAME::GraphicsCanvas & __ptr64) __ptr64
#define GD_DRAW_0GRAPHICSPRIMITIVEDRAWER "??0GraphicsPrimitiveDrawer@GAME@@QEAA@AEAVGraphicsCanvas@1@@Z"
// public: void __cdecl GAME::GraphicsPrimitiveDrawer::Begin(enum GAME::GraphicsPrimitiveDrawer::PrimitiveType) __ptr64
#define GD_DRAW_BEGIN "?Begin@GraphicsPrimitiveDrawer@GAME@@QEAAXW4PrimitiveType@12@@Z"
// void __cdecl GAME::Draw2DOrientedQuad(class GAME::GraphicsPrimitiveDrawer & __ptr64,class GAME::Vec2 const & __ptr64,class GAME::Vec2 const & __ptr64,class GAME::Vec2 const & __ptr64)
#define GD_DRAW_DRAW2DORIENTEDQUAD "?Draw2DOrientedQuad@GAME@@YAXAEAVGraphicsPrimitiveDrawer@1@AEBVVec2@1@11@Z"
// void __cdecl GAME::Draw2DRectangle(class GAME::GraphicsPrimitiveDrawer & __ptr64,class GAME::Rect const & __ptr64,class GAME::Rect const & __ptr64)
#define GD_DRAW_DRAW2DRECTANGLE "?Draw2DRectangle@GAME@@YAXAEAVGraphicsPrimitiveDrawer@1@AEBVRect@1@1@Z"
// void __cdecl GAME::Draw2DRectangle(class GAME::GraphicsPrimitiveDrawer & __ptr64,class GAME::Rect const & __ptr64)
#define GD_DRAW_DRAW2DRECTANGLE_2 "?Draw2DRectangle@GAME@@YAXAEAVGraphicsPrimitiveDrawer@1@AEBVRect@1@@Z"
// void __cdecl GAME::Draw2DRectangle(class GAME::GraphicsPrimitiveDrawer & __ptr64,class GAME::Rect const & __ptr64,float)
#define GD_DRAW_DRAW2DRECTANGLE_3 "?Draw2DRectangle@GAME@@YAXAEAVGraphicsPrimitiveDrawer@1@AEBVRect@1@M@Z"
// public: void __cdecl GAME::GraphicsPrimitiveDrawer::Enable2DMode(class GAME::Viewport const & __ptr64,float) __ptr64
#define GD_DRAW_ENABLE2DMODE "?Enable2DMode@GraphicsPrimitiveDrawer@GAME@@QEAAXAEBVViewport@2@M@Z"
// public: void __cdecl GAME::GraphicsPrimitiveDrawer::End(void) __ptr64
#define GD_DRAW_END "?End@GraphicsPrimitiveDrawer@GAME@@QEAAXXZ"
// public: void __cdecl GAME::GraphicsPrimitiveDrawer::Flush(void) __ptr64
#define GD_DRAW_FLUSH "?Flush@GraphicsPrimitiveDrawer@GAME@@QEAAXXZ"
// public: void __cdecl GAME::GraphicsPrimitiveDrawer::SetColor(class GAME::Color const & __ptr64) __ptr64
#define GD_DRAW_SETCOLOR "?SetColor@GraphicsPrimitiveDrawer@GAME@@QEAAXAEBVColor@2@@Z"
// public: void __cdecl GAME::GraphicsPrimitiveDrawer::SetTexture0(class GAME::RenderTexture const * __ptr64) __ptr64
#define GD_DRAW_SETTEXTURE0 "?SetTexture0@GraphicsPrimitiveDrawer@GAME@@QEAAXPEBVRenderTexture@2@@Z"

// ---------------------------------------------------------------------------------------------
// Window and input   [Engine.dll]
// ---------------------------------------------------------------------------------------------
// public: virtual int __cdecl GAME::WinWindow::GetClientHeight(void)const __ptr64
#define GD_WINDOW_GETCLIENTHEIGHT "?GetClientHeight@WinWindow@GAME@@UEBAHXZ"
// public: virtual int __cdecl GAME::WinWindow::GetClientWidth(void)const __ptr64
#define GD_WINDOW_GETCLIENTWIDTH "?GetClientWidth@WinWindow@GAME@@UEBAHXZ"
// public: virtual struct HWND__ * __ptr64 __cdecl GAME::WinWindow::GetSystemWindow(void)const __ptr64
#define GD_WINDOW_GETSYSTEMWINDOW "?GetSystemWindow@WinWindow@GAME@@UEBAPEAUHWND__@@XZ"
// public: virtual void __cdecl GAME::WinWindow::RegisterEventHandler(class GAME::WindowEventHandler * __ptr64) __ptr64
#define GD_WINDOW_REGISTEREVENTHANDLER "?RegisterEventHandler@WinWindow@GAME@@UEAAXPEAVWindowEventHandler@2@@Z"
// public: virtual void __cdecl GAME::WinWindow::UnregisterEventHandler(class GAME::WindowEventHandler * __ptr64) __ptr64
#define GD_WINDOW_UNREGISTEREVENTHANDLER "?UnregisterEventHandler@WinWindow@GAME@@UEAAXPEAVWindowEventHandler@2@@Z"
// private: static __int64 __cdecl GAME::WinWindow::WindowProc(struct HWND__ * __ptr64,unsigned int,unsigned __int64,__int64)
#define GD_WINDOW_WINDOWPROC "?WindowProc@WinWindow@GAME@@CA_JPEAUHWND__@@I_K_J@Z"

// ---------------------------------------------------------------------------------------------
// LocalizationManager (tag -> text)   [Engine.dll]
// ---------------------------------------------------------------------------------------------
// public: unsigned int __cdecl GAME::LocalizationManager::GetCurrentLanguage(void) __ptr64
#define GD_LOC_GETCURRENTLANGUAGE "?GetCurrentLanguage@LocalizationManager@GAME@@QEAAIXZ"
// public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64 __cdecl GAME::LocalizationManager::GetLanguage(void)const __ptr64
#define GD_LOC_GETLANGUAGE "?GetLanguage@LocalizationManager@GAME@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ"
// public: char const * __ptr64 __cdecl GAME::LocalizationManager::GetLanguageString(class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > const & __ptr64) __ptr64
#define GD_LOC_GETLANGUAGESTRING "?GetLanguageString@LocalizationManager@GAME@@QEAAPEBDAEBV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z"
// public: char const * __ptr64 __cdecl GAME::LocalizationManager::GetLanguageString(int) __ptr64
#define GD_LOC_GETLANGUAGESTRING_2 "?GetLanguageString@LocalizationManager@GAME@@QEAAPEBDH@Z"
// public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl GAME::LocalizationManager::GetLanguageTag(int) __ptr64  [returns by value -> hidden sret pointer as arg 2]
#define GD_LOC_GETLANGUAGETAG "?GetLanguageTag@LocalizationManager@GAME@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z"
// protected: class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > __cdecl GAME::LocalizationManager::GetText(char const * __ptr64) __ptr64
#define GD_LOC_GETTEXT "?GetText@LocalizationManager@GAME@@IEAA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@PEBD@Z"
// public: static class GAME::LocalizationManager & __ptr64 __cdecl GAME::LocalizationManager::Instance(void)
#define GD_LOC_INSTANCE "?Instance@LocalizationManager@GAME@@SAAEAV12@XZ"

// ---------------------------------------------------------------------------------------------
// Object lookup candidates (id -> Item*) - UNVERIFIED, see notes   [Engine.dll]
// ---------------------------------------------------------------------------------------------
// public: static class GAME::ObjectManager * __ptr64 __cdecl GAME::Singleton<class GAME::ObjectManager>::Get(void)
#define GD_OBJ_GET "?Get@?$Singleton@VObjectManager@GAME@@@GAME@@SAPEAVObjectManager@2@XZ"
// public: static class GAME::UniqueIdMap * __ptr64 __cdecl GAME::UniqueIdMap::Get(void)
#define GD_OBJ_GET_2 "?Get@UniqueIdMap@GAME@@SAPEAV12@XZ"
// public: class GAME::Entity * __ptr64 __cdecl GAME::UniqueIdMap::GetEntity(class GAME::UniqueId const & __ptr64)const __ptr64
#define GD_OBJ_GETENTITY "?GetEntity@UniqueIdMap@GAME@@QEBAPEAVEntity@2@AEBVUniqueId@2@@Z"
// public: unsigned int __cdecl GAME::ObjectManager::GetNumDeletedObjects(void)const __ptr64
#define GD_OBJ_GETNUMDELETEDOBJECTS "?GetNumDeletedObjects@ObjectManager@GAME@@QEBAIXZ"
// public: unsigned int __cdecl GAME::ObjectManager::GetNumObjects(void)const __ptr64
#define GD_OBJ_GETNUMOBJECTS "?GetNumObjects@ObjectManager@GAME@@QEBAIXZ"
// public: unsigned int __cdecl GAME::Object::GetObjectId(void)const __ptr64
#define GD_OBJ_GETOBJECTID "?GetObjectId@Object@GAME@@QEBAIXZ"
// public: void __cdecl GAME::ObjectManager::GetObjectList(class mem::vector<class GAME::Object const * __ptr64> & __ptr64)const __ptr64
#define GD_OBJ_GETOBJECTLIST "?GetObjectList@ObjectManager@GAME@@QEBAXAEAV?$vector@PEBVObject@GAME@@@mem@@@Z"
// public: char const * __ptr64 __cdecl GAME::Object::GetObjectName(void)const __ptr64
#define GD_OBJ_GETOBJECTNAME "?GetObjectName@Object@GAME@@QEBAPEBDXZ"
// public: unsigned int __cdecl GAME::Object::GetObjectNameHash(void)const __ptr64
#define GD_OBJ_GETOBJECTNAMEHASH "?GetObjectNameHash@Object@GAME@@QEBAIXZ"

// ---------------------------------------------------------------------------------------------
// GameEngine - stash / transfer   [Game.dll]
// ---------------------------------------------------------------------------------------------
// public: bool __cdecl GAME::GameEngine::DisplayCaravanWindow(unsigned int) __ptr64
#define GD_GAMEENGINE_DISPLAYCARAVANWINDOW "?DisplayCaravanWindow@GameEngine@GAME@@QEAA_NI@Z"
// public: static unsigned int const GAME::GameEngine::Expansion1MaxTransferSacks
#define GD_GAMEENGINE_EXPANSION1MAXTRANSFERSACKS "?Expansion1MaxTransferSacks@GameEngine@GAME@@2IB"
// public: static unsigned int const GAME::GameEngine::Expansion2MaxTransferSacks
#define GD_GAMEENGINE_EXPANSION2MAXTRANSFERSACKS "?Expansion2MaxTransferSacks@GameEngine@GAME@@2IB"
// public: static unsigned int const GAME::GameEngine::Expansion3MaxTransferSacks
#define GD_GAMEENGINE_EXPANSION3MAXTRANSFERSACKS "?Expansion3MaxTransferSacks@GameEngine@GAME@@2IB"
// public: class mem::vector<class GAME::InventorySack * __ptr64> & __ptr64 __cdecl GAME::GameEngine::GetPlayerTransfer(void) __ptr64
#define GD_GAMEENGINE_GETPLAYERTRANSFER "?GetPlayerTransfer@GameEngine@GAME@@QEAAAEAV?$vector@PEAVInventorySack@GAME@@@mem@@XZ"
// public: unsigned int __cdecl GAME::GameEngine::GetSelectedTransferSackNumber(void)const __ptr64
#define GD_GAMEENGINE_GETSELECTEDTRANSFERSACKNUMBER "?GetSelectedTransferSackNumber@GameEngine@GAME@@QEBAIXZ"
// public: int __cdecl GAME::GameEngine::GetTransferItemCount(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,class mem::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > const & __ptr64,class mem::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > const & __ptr64,class mem::vector<unsigned int> & __ptr64,bool,bool,bool)const __ptr64
#define GD_GAMEENGINE_GETTRANSFERITEMCOUNT "?GetTransferItemCount@GameEngine@GAME@@QEBAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@mem@@1AEAV?$vector@I@6@_N33@Z"
// public: class GAME::InventorySack * __ptr64 __cdecl GAME::GameEngine::GetTransferSack(int) __ptr64
#define GD_GAMEENGINE_GETTRANSFERSACK "?GetTransferSack@GameEngine@GAME@@QEAAPEAVInventorySack@2@H@Z"
// public: bool __cdecl GAME::GameEngine::IsTransferOpen(void)const __ptr64
#define GD_GAMEENGINE_ISTRANSFEROPEN "?IsTransferOpen@GameEngine@GAME@@QEBA_NXZ"
// public: static unsigned int const GAME::GameEngine::MaxTransferSacks
#define GD_GAMEENGINE_MAXTRANSFERSACKS "?MaxTransferSacks@GameEngine@GAME@@2IB"
// public: void __cdecl GAME::GameEngine::SetSelectedTransferSackNumber(unsigned int) __ptr64
#define GD_GAMEENGINE_SETSELECTEDTRANSFERSACKNUMBER "?SetSelectedTransferSackNumber@GameEngine@GAME@@QEAAXI@Z"
// public: void __cdecl GAME::GameEngine::SetTransferOpen(bool) __ptr64
#define GD_GAMEENGINE_SETTRANSFEROPEN "?SetTransferOpen@GameEngine@GAME@@QEAAX_N@Z"
// public: void __cdecl GAME::GameEngine::Update(int) __ptr64
#define GD_GAMEENGINE_UPDATE "?Update@GameEngine@GAME@@QEAAXH@Z"

// ---------------------------------------------------------------------------------------------
// GameEngine - database, UI metrics, item presentation   [Game.dll]
// ---------------------------------------------------------------------------------------------
// public: class GAME::LoadTable const & __ptr64 __cdecl GAME::GameEngine::GetDatabase(void)const __ptr64
#define GD_GAMEENGINE_GETDATABASE "?GetDatabase@GameEngine@GAME@@QEBAAEBVLoadTable@2@XZ"
// public: void __cdecl GAME::GameEngine::GetInventoryCellSize(float & __ptr64,float & __ptr64) __ptr64
#define GD_GAMEENGINE_GETINVENTORYCELLSIZE "?GetInventoryCellSize@GameEngine@GAME@@QEAAXAEAM0@Z"
// public: class GAME::GraphicsTexture const * __ptr64 __cdecl GAME::GameEngine::GetItemBackground(enum GAME::ItemClassification)const __ptr64
#define GD_GAMEENGINE_GETITEMBACKGROUND "?GetItemBackground@GameEngine@GAME@@QEBAPEBVGraphicsTexture@2@W4ItemClassification@2@@Z"
// public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl GAME::GameEngine::GetItemClassificationName(enum GAME::ItemClassification,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)const __ptr64  [returns by value -> hidden sret pointer as arg 2]
#define GD_GAMEENGINE_GETITEMCLASSIFICATIONNAME "?GetItemClassificationName@GameEngine@GAME@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4ItemClassification@2@V34@@Z"
// public: class GAME::Color __cdecl GAME::GameEngine::GetItemColor(enum GAME::ItemClassification)const __ptr64  [returns by value -> hidden sret pointer as arg 2]
#define GD_GAMEENGINE_GETITEMCOLOR "?GetItemColor@GameEngine@GAME@@QEBA?AVColor@2@W4ItemClassification@2@@Z"
// public: class GAME::Player * __ptr64 __cdecl GAME::GameEngine::GetMainPlayer(void)const __ptr64
#define GD_GAMEENGINE_GETMAINPLAYER "?GetMainPlayer@GameEngine@GAME@@QEBAPEAVPlayer@2@XZ"

// ---------------------------------------------------------------------------------------------
// Player - private stash   [Game.dll]
// ---------------------------------------------------------------------------------------------
// public: void __cdecl GAME::Player::GetCompatibleStash(unsigned int,class mem::vector<unsigned int> & __ptr64) __ptr64
#define GD_PLAYER_GETCOMPATIBLESTASH "?GetCompatibleStash@Player@GAME@@QEAAXIAEAV?$vector@I@mem@@@Z"
// public: virtual int __cdecl GAME::Player::GetItemCountInStashes(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,class mem::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > const & __ptr64,class mem::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > const & __ptr64,class mem::vector<unsigned int> & __ptr64,bool,bool,bool,bool)const __ptr64
#define GD_PLAYER_GETITEMCOUNTINSTASHES "?GetItemCountInStashes@Player@GAME@@UEBAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@mem@@1AEAV?$vector@I@6@_N333@Z"
// public: static unsigned int __cdecl GAME::Player::GetMaximumSacks(void)
#define GD_PLAYER_GETMAXIMUMSACKS "?GetMaximumSacks@Player@GAME@@SAIXZ"
// public: class mem::vector<class GAME::InventorySack * __ptr64> & __ptr64 __cdecl GAME::Player::GetPrivateStash(void) __ptr64
#define GD_PLAYER_GETPRIVATESTASH "?GetPrivateStash@Player@GAME@@QEAAAEAV?$vector@PEAVInventorySack@GAME@@@mem@@XZ"
// public: class GAME::InventorySack * __ptr64 __cdecl GAME::Player::GetSack(int) __ptr64
#define GD_PLAYER_GETSACK "?GetSack@Player@GAME@@QEAAPEAVInventorySack@2@H@Z"
// public: unsigned int __cdecl GAME::Player::GetSelectedStashSackNumber(void)const __ptr64
#define GD_PLAYER_GETSELECTEDSTASHSACKNUMBER "?GetSelectedStashSackNumber@Player@GAME@@QEBAIXZ"
// public: void __cdecl GAME::Player::SetSelectedStashSackNumber(unsigned int) __ptr64
#define GD_PLAYER_SETSELECTEDSTASHSACKNUMBER "?SetSelectedStashSackNumber@Player@GAME@@QEAAXI@Z"

// ---------------------------------------------------------------------------------------------
// InventorySack - every exported method   [Game.dll]
// ---------------------------------------------------------------------------------------------
// public: bool __cdecl GAME::InventorySack::AddItem(class GAME::Vec2 const & __ptr64,class GAME::Item * __ptr64,bool) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_ADDITEM "?AddItem@InventorySack@GAME@@QEAA_NAEBVVec2@2@PEAVItem@2@_N@Z"
// public: bool __cdecl GAME::InventorySack::AddItem(class GAME::Item * __ptr64,bool,bool) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_ADDITEM_2 "?AddItem@InventorySack@GAME@@QEAA_NPEAVItem@2@_N1@Z"
// public: class GAME::Vec2 __cdecl GAME::InventorySack::AddItemAndReturnPoint(class GAME::Item * __ptr64) __ptr64  ** WRITE - do not call in M1-M4 **  [returns by value -> hidden sret pointer as arg 2]
#define GD_SACK_ADDITEMANDRETURNPOINT "?AddItemAndReturnPoint@InventorySack@GAME@@QEAA?AVVec2@2@PEAVItem@2@@Z"
// public: void __cdecl GAME::InventorySack::AlignRect(class GAME::Rect & __ptr64)const __ptr64
#define GD_SACK_ALIGNRECT "?AlignRect@InventorySack@GAME@@QEBAXAEAVRect@2@@Z"
// public: bool __cdecl GAME::InventorySack::ArrangeUnpositionedItems(void) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_ARRANGEUNPOSITIONEDITEMS "?ArrangeUnpositionedItems@InventorySack@GAME@@QEAA_NXZ"
// public: void __cdecl GAME::InventorySack::CompleteRelics(class GAME::Player * __ptr64) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_COMPLETERELICS "?CompleteRelics@InventorySack@GAME@@QEAAXPEAVPlayer@2@@Z"
// public: bool __cdecl GAME::InventorySack::ContainsItem(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64)const __ptr64
#define GD_SACK_CONTAINSITEM "?ContainsItem@InventorySack@GAME@@QEBA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z"
// public: bool __cdecl GAME::InventorySack::ContainsItem(unsigned int)const __ptr64
#define GD_SACK_CONTAINSITEM_2 "?ContainsItem@InventorySack@GAME@@QEBA_NI@Z"
// public: void __cdecl GAME::InventorySack::DeleteAndCreateAllItemsFor(class GAME::ControllerPlayer * __ptr64) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_DELETEANDCREATEALLITEMSFOR "?DeleteAndCreateAllItemsFor@InventorySack@GAME@@QEAAXPEAVControllerPlayer@2@@Z"
// public: bool __cdecl GAME::InventorySack::DepositSackIntoReagents(class GAME::ControllerPlayer * __ptr64) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_DEPOSITSACKINTOREAGENTS "?DepositSackIntoReagents@InventorySack@GAME@@QEAA_NPEAVControllerPlayer@2@@Z"
// public: void __cdecl GAME::InventorySack::DestroyAllItems(void) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_DESTROYALLITEMS "?DestroyAllItems@InventorySack@GAME@@QEAAXXZ"
// protected: bool __cdecl GAME::InventorySack::FindNextPosition(class GAME::Item const * __ptr64,class GAME::Rect & __ptr64,bool)const __ptr64
#define GD_SACK_FINDNEXTPOSITION "?FindNextPosition@InventorySack@GAME@@IEBA_NPEBVItem@2@AEAVRect@2@_N@Z"
// public: unsigned int __cdecl GAME::InventorySack::GetBorderColorIndex(void)const __ptr64
#define GD_SACK_GETBORDERCOLORINDEX "?GetBorderColorIndex@InventorySack@GAME@@QEBAIXZ"
// public: unsigned int __cdecl GAME::InventorySack::GetBorderIndex(void)const __ptr64
#define GD_SACK_GETBORDERINDEX "?GetBorderIndex@InventorySack@GAME@@QEBAIXZ"
// public: class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > const & __ptr64 __cdecl GAME::InventorySack::GetButtonName(void)const __ptr64
#define GD_SACK_GETBUTTONNAME "?GetButtonName@InventorySack@GAME@@QEBAAEBV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@XZ"
// public: unsigned int __cdecl GAME::InventorySack::GetCellHeight(void)const __ptr64
#define GD_SACK_GETCELLHEIGHT "?GetCellHeight@InventorySack@GAME@@QEBAIXZ"
// public: unsigned int __cdecl GAME::InventorySack::GetCellWidth(void)const __ptr64
#define GD_SACK_GETCELLWIDTH "?GetCellWidth@InventorySack@GAME@@QEBAIXZ"
// public: void __cdecl GAME::InventorySack::GetConflicts(class GAME::Vec2 const & __ptr64,class GAME::Item * __ptr64,class mem::vector<class GAME::Rect> & __ptr64,class GAME::Rect & __ptr64)const __ptr64
#define GD_SACK_GETCONFLICTS "?GetConflicts@InventorySack@GAME@@QEBAXAEBVVec2@2@PEAVItem@2@AEAV?$vector@VRect@GAME@@@mem@@AEAVRect@2@@Z"
// public: unsigned int __cdecl GAME::InventorySack::GetFirstItem(void) __ptr64
#define GD_SACK_GETFIRSTITEM "?GetFirstItem@InventorySack@GAME@@QEAAIXZ"
// public: unsigned int __cdecl GAME::InventorySack::GetGridHeight(void)const __ptr64
#define GD_SACK_GETGRIDHEIGHT "?GetGridHeight@InventorySack@GAME@@QEBAIXZ"
// public: unsigned int __cdecl GAME::InventorySack::GetGridWidth(void)const __ptr64
#define GD_SACK_GETGRIDWIDTH "?GetGridWidth@InventorySack@GAME@@QEBAIXZ"
// public: class mem::map<unsigned int,class GAME::Rect> & __ptr64 __cdecl GAME::InventorySack::GetInventory(void) __ptr64
#define GD_SACK_GETINVENTORY "?GetInventory@InventorySack@GAME@@QEAAAEAV?$map@IVRect@GAME@@@mem@@XZ"
// public: class mem::map<unsigned int,class GAME::Rect> const & __ptr64 __cdecl GAME::InventorySack::GetInventory(void)const __ptr64
#define GD_SACK_GETINVENTORY_2 "?GetInventory@InventorySack@GAME@@QEBAAEBV?$map@IVRect@GAME@@@mem@@XZ"
// public: int __cdecl GAME::InventorySack::GetItemCount(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,class mem::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > const & __ptr64,class mem::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > const & __ptr64,class mem::vector<unsigned int> & __ptr64,bool,bool,bool)const __ptr64
#define GD_SACK_GETITEMCOUNT "?GetItemCount@InventorySack@GAME@@QEBAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@mem@@1AEAV?$vector@I@6@_N33@Z"
// public: class GAME::Vec2 __cdecl GAME::InventorySack::GetItemPosition(unsigned int)const __ptr64  [returns by value -> hidden sret pointer as arg 2]
#define GD_SACK_GETITEMPOSITION "?GetItemPosition@InventorySack@GAME@@QEBA?AVVec2@2@I@Z"
// public: unsigned int __cdecl GAME::InventorySack::GetItemUnderPoint(class GAME::Vec2)const __ptr64
#define GD_SACK_GETITEMUNDERPOINT "?GetItemUnderPoint@InventorySack@GAME@@QEBAIVVec2@2@@Z"
// public: unsigned int __cdecl GAME::InventorySack::GetNotFullItem(class GAME::Item const * __ptr64,bool)const __ptr64
#define GD_SACK_GETNOTFULLITEM "?GetNotFullItem@InventorySack@GAME@@QEBAIPEBVItem@2@_N@Z"
// public: unsigned int __cdecl GAME::InventorySack::GetNotFullRelic(class GAME::Item const * __ptr64)const __ptr64
#define GD_SACK_GETNOTFULLRELIC "?GetNotFullRelic@InventorySack@GAME@@QEBAIPEBVItem@2@@Z"
// public: class GAME::Rect __cdecl GAME::InventorySack::GetRectUnderPoint(class GAME::Vec2)const __ptr64  [returns by value -> hidden sret pointer as arg 2]
#define GD_SACK_GETRECTUNDERPOINT "?GetRectUnderPoint@InventorySack@GAME@@QEBA?AVRect@2@VVec2@2@@Z"
// public: unsigned int __cdecl GAME::InventorySack::GetSymbolColorIndex(void)const __ptr64
#define GD_SACK_GETSYMBOLCOLORINDEX "?GetSymbolColorIndex@InventorySack@GAME@@QEBAIXZ"
// public: unsigned int __cdecl GAME::InventorySack::GetSymbolIndex(void)const __ptr64
#define GD_SACK_GETSYMBOLINDEX "?GetSymbolIndex@InventorySack@GAME@@QEBAIXZ"
// public: void __cdecl GAME::InventorySack::GiveAllItems(class GAME::ControllerPlayer * __ptr64) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_GIVEALLITEMS "?GiveAllItems@InventorySack@GAME@@QEAAXPEAVControllerPlayer@2@@Z"
// public: class GAME::Vec2 __cdecl GAME::InventorySack::GridToPixels(class GAME::Vec2 const & __ptr64)const __ptr64  [returns by value -> hidden sret pointer as arg 2]
#define GD_SACK_GRIDTOPIXELS "?GridToPixels@InventorySack@GAME@@QEBA?AVVec2@2@AEBV32@@Z"
// protected: bool __cdecl GAME::InventorySack::IsConflict(class GAME::Rect const & __ptr64,bool)const __ptr64
#define GD_SACK_ISCONFLICT "?IsConflict@InventorySack@GAME@@IEBA_NAEBVRect@2@_N@Z"
// public: bool __cdecl GAME::InventorySack::IsItemAddedWhileNotTheCurrentlySelectedInventoryTab(void) __ptr64
#define GD_SACK_ISITEMADDEDWHILENOTTHECURRENTLYSELECTEDINVENTORYTAB "?IsItemAddedWhileNotTheCurrentlySelectedInventoryTab@InventorySack@GAME@@QEAA_NXZ"
// public: bool __cdecl GAME::InventorySack::IsSpaceForItem(class GAME::Item const * __ptr64,bool)const __ptr64
#define GD_SACK_ISSPACEFORITEM "?IsSpaceForItem@InventorySack@GAME@@QEBA_NPEBVItem@2@_N@Z"
// public: bool __cdecl GAME::InventorySack::LoadSackIntoTransmutes(void) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_LOADSACKINTOTRANSMUTES "?LoadSackIntoTransmutes@InventorySack@GAME@@QEAA_NXZ"
// public: class GAME::Vec2 __cdecl GAME::InventorySack::PixelsToGrid(class GAME::Vec2 const & __ptr64)const __ptr64  [returns by value -> hidden sret pointer as arg 2]
#define GD_SACK_PIXELSTOGRID "?PixelsToGrid@InventorySack@GAME@@QEBA?AVVec2@2@AEBV32@@Z"
// public: void __cdecl GAME::InventorySack::RemoveAllItems(void) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_REMOVEALLITEMS "?RemoveAllItems@InventorySack@GAME@@QEAAXXZ"
// public: bool __cdecl GAME::InventorySack::RemoveItem(unsigned int) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_REMOVEITEM "?RemoveItem@InventorySack@GAME@@QEAA_NI@Z"
// public: bool __cdecl GAME::InventorySack::ReplaceItem(unsigned int,unsigned int) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_REPLACEITEM "?ReplaceItem@InventorySack@GAME@@QEAA_NII@Z"
// protected: bool __cdecl GAME::InventorySack::SearchHorizantal(class GAME::Rect & __ptr64,bool)const __ptr64
#define GD_SACK_SEARCHHORIZANTAL "?SearchHorizantal@InventorySack@GAME@@IEBA_NAEAVRect@2@_N@Z"
// public: void __cdecl GAME::InventorySack::SearchItems(class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > const & __ptr64,class mem::vector<class GAME::Rect> & __ptr64,class mem::vector<class GAME::Rect> & __ptr64) __ptr64
#define GD_SACK_SEARCHITEMS "?SearchItems@InventorySack@GAME@@QEAAXAEBV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@AEAV?$vector@VRect@GAME@@@mem@@1@Z"
// protected: bool __cdecl GAME::InventorySack::SearchVertical(class GAME::Rect & __ptr64,bool)const __ptr64
#define GD_SACK_SEARCHVERTICAL "?SearchVertical@InventorySack@GAME@@IEBA_NAEAVRect@2@_N@Z"
// public: void __cdecl GAME::InventorySack::SetBorder(unsigned int) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_SETBORDER "?SetBorder@InventorySack@GAME@@QEAAXI@Z"
// public: void __cdecl GAME::InventorySack::SetBorderColor(unsigned int) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_SETBORDERCOLOR "?SetBorderColor@InventorySack@GAME@@QEAAXI@Z"
// public: void __cdecl GAME::InventorySack::SetButtonName(class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> >) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_SETBUTTONNAME "?SetButtonName@InventorySack@GAME@@QEAAXV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z"
// public: void __cdecl GAME::InventorySack::SetDims(int,int,bool) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_SETDIMS "?SetDims@InventorySack@GAME@@QEAAXHH_N@Z"
// public: void __cdecl GAME::InventorySack::SetItemAddedWhileNotTheCurrentlySelectedInventoryTab(bool) __ptr64
#define GD_SACK_SETITEMADDEDWHILENOTTHECURRENTLYSELECTEDINVENTORYTAB "?SetItemAddedWhileNotTheCurrentlySelectedInventoryTab@InventorySack@GAME@@QEAAX_N@Z"
// public: void __cdecl GAME::InventorySack::SetSymbol(unsigned int) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_SETSYMBOL "?SetSymbol@InventorySack@GAME@@QEAAXI@Z"
// public: void __cdecl GAME::InventorySack::SetSymbolColor(unsigned int) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_SETSYMBOLCOLOR "?SetSymbolColor@InventorySack@GAME@@QEAAXI@Z"
// public: bool __cdecl GAME::InventorySack::Sort(unsigned int) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_SORT "?Sort@InventorySack@GAME@@QEAA_NI@Z"
// public: void __cdecl GAME::InventorySack::TakeAllItems(class GAME::ControllerPlayer * __ptr64) __ptr64  ** WRITE - do not call in M1-M4 **
#define GD_SACK_TAKEALLITEMS "?TakeAllItems@InventorySack@GAME@@QEAAXPEAVControllerPlayer@2@@Z"

// ---------------------------------------------------------------------------------------------
// Item   [Game.dll]
// ---------------------------------------------------------------------------------------------
// public: virtual bool __cdecl GAME::Item::CanBePlacedInTransferStash(void)const __ptr64
#define GD_ITEM_CANBEPLACEDINTRANSFERSTASH "?CanBePlacedInTransferStash@Item@GAME@@UEBA_NXZ"
// public: bool __cdecl GAME::Item::CannotPickUp(void)const __ptr64
#define GD_ITEM_CANNOTPICKUP "?CannotPickUp@Item@GAME@@QEBA_NXZ"
// public: bool __cdecl GAME::Item::CannotPickUpMultiple(void)const __ptr64
#define GD_ITEM_CANNOTPICKUPMULTIPLE "?CannotPickUpMultiple@Item@GAME@@QEBA_NXZ"
// public: static class GAME::Item * __ptr64 __cdecl GAME::Item::CreateItem(struct GAME::ItemReplicaInfo const & __ptr64)  ** WRITE - do not call in M1-M4 **
#define GD_ITEM_CREATEITEM "?CreateItem@Item@GAME@@SAPEAV12@AEBUItemReplicaInfo@2@@Z"
// public: virtual class GAME::GraphicsTexture const * __ptr64 __cdecl GAME::Item::GetBitmap(void)const __ptr64
#define GD_ITEM_GETBITMAP "?GetBitmap@Item@GAME@@UEBAPEBVGraphicsTexture@2@XZ"
// public: virtual void __cdecl GAME::Item::GetBitmapName(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > & __ptr64)const __ptr64
#define GD_ITEM_GETBITMAPNAME "?GetBitmapName@Item@GAME@@UEBAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z"
// public: enum GAME::ItemClassification __cdecl GAME::Item::GetDropClassification(void)const __ptr64
#define GD_ITEM_GETDROPCLASSIFICATION "?GetDropClassification@Item@GAME@@QEBA?AW4ItemClassification@2@XZ"
// public: virtual class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > __cdecl GAME::Item::GetGameDescription(bool,bool)const __ptr64
#define GD_ITEM_GETGAMEDESCRIPTION "?GetGameDescription@Item@GAME@@UEBA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@_N0@Z"
// public: virtual enum GAME::ItemClassification __cdecl GAME::Item::GetItemClassification(bool)const __ptr64
#define GD_ITEM_GETITEMCLASSIFICATION "?GetItemClassification@Item@GAME@@UEBA?AW4ItemClassification@2@_N@Z"
// public: unsigned int __cdecl GAME::Item::GetItemLevel(void)const __ptr64
#define GD_ITEM_GETITEMLEVEL "?GetItemLevel@Item@GAME@@QEBAIXZ"
// public: virtual void __cdecl GAME::Item::GetItemReplicaInfo(struct GAME::ItemReplicaInfo & __ptr64)const __ptr64
#define GD_ITEM_GETITEMREPLICAINFO "?GetItemReplicaInfo@Item@GAME@@UEBAXAEAUItemReplicaInfo@2@@Z"
// public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64 __cdecl GAME::Item::GetItemTextTag(void)const __ptr64
#define GD_ITEM_GETITEMTEXTTAG "?GetItemTextTag@Item@GAME@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ"
// public: virtual enum GAME::Item_Type const __cdecl GAME::Item::GetItemType(void)const __ptr64
#define GD_ITEM_GETITEMTYPE "?GetItemType@Item@GAME@@UEBA?BW4Item_Type@2@XZ"
// public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl GAME::Item::GetItemTypeTag(enum GAME::Item_Type)
#define GD_ITEM_GETITEMTYPETAG "?GetItemTypeTag@Item@GAME@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4Item_Type@2@@Z"
// public: virtual unsigned int __cdecl GAME::Item::GetLevelRequirement(void)const __ptr64
#define GD_ITEM_GETLEVELREQUIREMENT "?GetLevelRequirement@Item@GAME@@UEBAIXZ"
// public: virtual unsigned int __cdecl GAME::Item::GetMaxStackSize(void)const __ptr64
#define GD_ITEM_GETMAXSTACKSIZE "?GetMaxStackSize@Item@GAME@@UEBAIXZ"
// public: virtual void __cdecl GAME::Item::GetRolloverSize(float & __ptr64,float & __ptr64) __ptr64
#define GD_ITEM_GETROLLOVERSIZE "?GetRolloverSize@Item@GAME@@UEAAXAEAM0@Z"
// public: unsigned int __cdecl GAME::Item::GetSeedRerolls(void)const __ptr64
#define GD_ITEM_GETSEEDREROLLS "?GetSeedRerolls@Item@GAME@@QEBAIXZ"
// public: virtual class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > __cdecl GAME::Item::GetSimpleDescription(void)const __ptr64
#define GD_ITEM_GETSIMPLEDESCRIPTION "?GetSimpleDescription@Item@GAME@@UEBA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@XZ"
// public: virtual unsigned int __cdecl GAME::Item::GetStackSize(void)const __ptr64
#define GD_ITEM_GETSTACKSIZE "?GetStackSize@Item@GAME@@UEBAIXZ"
// public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl GAME::Item::GetSymbolBitmapName(void)const __ptr64
#define GD_ITEM_GETSYMBOLBITMAPNAME "?GetSymbolBitmapName@Item@GAME@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ"
// public: virtual class GAME::GraphicsTexture const * __ptr64 __cdecl GAME::Item::GetUIBitmapOverlay(void)const __ptr64
#define GD_ITEM_GETUIBITMAPOVERLAY "?GetUIBitmapOverlay@Item@GAME@@UEBAPEBVGraphicsTexture@2@XZ"
// public: virtual void __cdecl GAME::Item::GetUIBitmapText(class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > & __ptr64,bool)const __ptr64
#define GD_ITEM_GETUIBITMAPTEXT "?GetUIBitmapText@Item@GAME@@UEBAXAEAV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@_N@Z"
// public: virtual void __cdecl GAME::Item::GetUIDisplayText(class GAME::Character const * __ptr64,class mem::vector<struct GAME::GameTextLine> & __ptr64,bool)const __ptr64
#define GD_ITEM_GETUIDISPLAYTEXT "?GetUIDisplayText@Item@GAME@@UEBAXPEBVCharacter@2@AEAV?$vector@UGameTextLine@GAME@@@mem@@_N@Z"
// public: bool __cdecl GAME::Item::IsItemAvailable(class GAME::Character const * __ptr64,unsigned int,unsigned int,unsigned int)const __ptr64
#define GD_ITEM_ISITEMAVAILABLE "?IsItemAvailable@Item@GAME@@QEBA_NPEBVCharacter@2@III@Z"
// public: bool __cdecl GAME::Item::IsReagentCompatible(void)const __ptr64
#define GD_ITEM_ISREAGENTCOMPATIBLE "?IsReagentCompatible@Item@GAME@@QEBA_NXZ"
// public: bool const __cdecl GAME::Item::IsSoulbound(void)const __ptr64
#define GD_ITEM_ISSOULBOUND "?IsSoulbound@Item@GAME@@QEBA?B_NXZ"
// public: bool const __cdecl GAME::Item::IsUntradeable(void)const __ptr64
#define GD_ITEM_ISUNTRADEABLE "?IsUntradeable@Item@GAME@@QEBA?B_NXZ"
// public: bool __cdecl GAME::Item::PassLootFilter(enum GAME::InGameUIActorCapture::ItemIgnore)const __ptr64
#define GD_ITEM_PASSLOOTFILTER "?PassLootFilter@Item@GAME@@QEBA_NW4ItemIgnore@InGameUIActorCapture@2@@Z"

// ---------------------------------------------------------------------------------------------
// ItemEquipment   [Game.dll]
// ---------------------------------------------------------------------------------------------
// public: virtual class GAME::GraphicsTexture const * __ptr64 __cdecl GAME::ItemEquipment::GetBitmap(void)const __ptr64
#define GD_ITEMEQUIP_GETBITMAP "?GetBitmap@ItemEquipment@GAME@@UEBAPEBVGraphicsTexture@2@XZ"
// public: virtual void __cdecl GAME::ItemEquipment::GetBitmapName(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > & __ptr64)const __ptr64
#define GD_ITEMEQUIP_GETBITMAPNAME "?GetBitmapName@ItemEquipment@GAME@@UEBAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z"
// public: class GAME::ItemEnchantment * __ptr64 __cdecl GAME::ItemEquipment::GetEnchantment(void)const __ptr64
#define GD_ITEMEQUIP_GETENCHANTMENT "?GetEnchantment@ItemEquipment@GAME@@QEBAPEAVItemEnchantment@2@XZ"
// public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64 __cdecl GAME::ItemEquipment::GetItemSetName(void)const __ptr64
#define GD_ITEMEQUIP_GETITEMSETNAME "?GetItemSetName@ItemEquipment@GAME@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ"
// public: virtual unsigned int __cdecl GAME::ItemEquipment::GetLevelRequirement(void)const __ptr64
#define GD_ITEMEQUIP_GETLEVELREQUIREMENT "?GetLevelRequirement@ItemEquipment@GAME@@UEBAIXZ"
// public: class GAME::ItemRelic * __ptr64 __cdecl GAME::ItemEquipment::GetRelic(void)const __ptr64
#define GD_ITEMEQUIP_GETRELIC "?GetRelic@ItemEquipment@GAME@@QEBAPEAVItemRelic@2@XZ"
// public: void __cdecl GAME::ItemEquipment::GetSearchText(class GAME::Character const * __ptr64,class mem::vector<struct GAME::GameTextLine> & __ptr64)const __ptr64
#define GD_ITEMEQUIP_GETSEARCHTEXT "?GetSearchText@ItemEquipment@GAME@@QEBAXPEBVCharacter@2@AEAV?$vector@UGameTextLine@GAME@@@mem@@@Z"
// public: virtual class GAME::GraphicsTexture const * __ptr64 __cdecl GAME::ItemEquipment::GetUIBitmapOverlay(void)const __ptr64
#define GD_ITEMEQUIP_GETUIBITMAPOVERLAY "?GetUIBitmapOverlay@ItemEquipment@GAME@@UEBAPEBVGraphicsTexture@2@XZ"
// public: virtual void __cdecl GAME::ItemEquipment::GetUIDisplayText(class GAME::Character const * __ptr64,class mem::vector<struct GAME::GameTextLine> & __ptr64,bool)const __ptr64
#define GD_ITEMEQUIP_GETUIDISPLAYTEXT "?GetUIDisplayText@ItemEquipment@GAME@@UEBAXPEBVCharacter@2@AEAV?$vector@UGameTextLine@GAME@@@mem@@_N@Z"
// public: bool __cdecl GAME::ItemEquipment::HasEnchantment(void)const __ptr64
#define GD_ITEMEQUIP_HASENCHANTMENT "?HasEnchantment@ItemEquipment@GAME@@QEBA_NXZ"
// public: bool __cdecl GAME::ItemEquipment::HasRelic(void)const __ptr64
#define GD_ITEMEQUIP_HASRELIC "?HasRelic@ItemEquipment@GAME@@QEBA_NXZ"


// ---------------------------------------------------------------------------------------------
// Suggested typedefs for the hook / call set (Microsoft x64 ABI, this-pointer first)
// ---------------------------------------------------------------------------------------------
// Opaque handles - never dereference these, always go through an exported accessor.
typedef struct GD_Engine        GD_Engine;
typedef struct GD_GraphicsEngine GD_GraphicsEngine;
typedef struct GD_Canvas        GD_Canvas;
typedef struct GD_Texture       GD_Texture;       // GAME::GraphicsTexture
typedef struct GD_RenderTexture GD_RenderTexture; // GAME::RenderTexture
typedef struct GD_Font          GD_Font;          // GAME::GraphicsFont2
typedef struct GD_GameEngine    GD_GameEngine;
typedef struct GD_Player        GD_Player;
typedef struct GD_Sack          GD_Sack;          // GAME::InventorySack
typedef struct GD_Item          GD_Item;
typedef struct GD_Rect          GD_Rect;          // layout unverified (probably 4 floats)
typedef struct GD_Vec2          GD_Vec2;          // layout unverified (probably 2 floats)
typedef struct GD_Color         GD_Color;         // layout unverified (probably 4 floats)
typedef struct GD_Viewport      GD_Viewport;
typedef struct GD_Name          GD_Name;

// Engine.dll
typedef GD_GraphicsEngine* (*GD_Engine_GetGraphicsEngine_t)(GD_Engine* self);
typedef void               (*GD_Engine_PresentSurface_t)(GD_Engine* self);
typedef unsigned int       (*GD_Engine_GetFrameCount_t)(GD_Engine* self);
typedef GD_Canvas*         (*GD_GfxEngine_GetCanvas_t)(GD_GraphicsEngine* self);          // returns a reference
typedef const GD_Texture*  (*GD_GfxEngine_LoadTexture_t)(GD_GraphicsEngine* self, const void* stdStringPath);
typedef const GD_Font*     (*GD_GfxEngine_LoadFont_t)(GD_GraphicsEngine* self, const void* stdStringPath);
typedef const GD_RenderTexture* (*GD_Texture_GetTexture_t)(const GD_Texture* self);
typedef int                (*GD_Canvas_GetWidth_t)(const GD_Canvas* self);
typedef int                (*GD_Canvas_GetHeight_t)(const GD_Canvas* self);
typedef void               (*GD_Canvas_RenderRectSolid_t)(GD_Canvas* self, const GD_Rect* r, const GD_Color* c);
typedef void               (*GD_Canvas_RenderRectTex_t)(GD_Canvas* self, const GD_Rect* dst, const GD_Rect* uv,
                                                        const GD_RenderTexture* tex, const GD_Color* tint);
typedef void               (*GD_Canvas_SetClippingRect_t)(GD_Canvas* self, const GD_Rect* r, bool intersect);
typedef void               (*GD_Canvas_ClearClippingRect_t)(GD_Canvas* self);
// CalcTextRect returns Rect by value -> hidden sret pointer as argument 2.
typedef GD_Rect*           (*GD_Canvas_CalcTextRect_t)(const GD_Canvas* self, GD_Rect* sret, GD_Rect text,
                                                       int x, int y, int xalign, int yalign);
// RenderText2d(int x, int y, const Color&, const Color& outline, const char*, const GraphicsFont2*,
//              int size, GraphicsXAlign, GraphicsYAlign, FontStyleFlag, FontLayout)
typedef void               (*GD_Canvas_RenderText2d_t)(GD_Canvas* self, int x, int y, const GD_Color* col,
                                                       const GD_Color* outline, const char* text,
                                                       const GD_Font* font, int size, int xalign, int yalign,
                                                       int styleFlags, int layout);

// Game.dll
typedef void        (*GD_GameEngine_SetTransferOpen_t)(GD_GameEngine* self, bool open);
typedef bool        (*GD_GameEngine_IsTransferOpen_t)(const GD_GameEngine* self);
typedef void        (*GD_GameEngine_Update_t)(GD_GameEngine* self, int deltaMs);
typedef void*       (*GD_GameEngine_GetPlayerTransfer_t)(GD_GameEngine* self);   // mem::vector<InventorySack*>&
typedef GD_Sack*    (*GD_GameEngine_GetTransferSack_t)(GD_GameEngine* self, int index);
typedef unsigned    (*GD_GameEngine_GetSelectedTransferSackNumber_t)(const GD_GameEngine* self);
typedef void        (*GD_GameEngine_SetSelectedTransferSackNumber_t)(GD_GameEngine* self, unsigned n);
typedef GD_Player*  (*GD_GameEngine_GetMainPlayer_t)(GD_GameEngine* self);
typedef void        (*GD_GameEngine_GetInventoryCellSize_t)(GD_GameEngine* self, float* w, float* h);
typedef const GD_Texture* (*GD_GameEngine_GetItemBackground_t)(const GD_GameEngine* self, int classification);
// int GetTransferItemCount(const std::string& record, const mem::vector<std::string>& a,
//                          const mem::vector<std::string>& b, mem::vector<unsigned>& out,
//                          bool f1, bool f2, bool f3) const
typedef int         (*GD_GameEngine_GetTransferItemCount_t)(const GD_GameEngine* self, const void* record,
                                                            const void* vecA, const void* vecB, void* outIds,
                                                            bool f1, bool f2, bool f3);
typedef void*       (*GD_Player_GetPrivateStash_t)(GD_Player* self);             // mem::vector<InventorySack*>&
typedef GD_Sack*    (*GD_Player_GetSack_t)(GD_Player* self, int index);
typedef const void* (*GD_Sack_GetInventory_t)(const GD_Sack* self);              // const mem::map<unsigned, Rect>&
typedef unsigned    (*GD_Sack_GetGridWidth_t)(const GD_Sack* self);
typedef bool        (*GD_Sack_ContainsItemById_t)(const GD_Sack* self, unsigned itemId);
typedef bool        (*GD_Sack_ContainsItemByRecord_t)(const GD_Sack* self, const void* stdStringRecord);
typedef void        (*GD_Item_GetItemReplicaInfo_t)(const GD_Item* self, void* outItemReplicaInfo);
typedef int         (*GD_Item_GetItemClassification_t)(const GD_Item* self, bool something);
typedef const GD_Texture* (*GD_Item_GetBitmap_t)(const GD_Item* self);
typedef void        (*GD_Item_GetBitmapName_t)(const GD_Item* self, void* outStdString);
// The InventorySack::AddItem hook signature (hooked to OBSERVE only, never called):
typedef bool        (*GD_Sack_AddItem_t)(GD_Sack* self, GD_Item* item, bool a, bool b);


#ifdef __cplusplus
}  // extern "C"
#endif
