// gd_exports_reagent.h - the reagent-page mangled names.
//
// GENERATED by tools/gen_reagent_header.py - do not hand-edit. Every name is
// copied verbatim out of tools/exports/{Game,Engine}-x64-exports.txt (1.3.0.8 x64)
// after being found there, so no mangled name is ever typed by hand.

#pragma once

// Game.dll : READ ONLY - not hooked; its 7 code bytes carry the craftingMaterial field offset
#define GD_ITEM_ISREAGENTCOMPATIBLE "?IsReagentCompatible@Item@GAME@@QEBA_NXZ"

// Game.dll : post-detour: the point where the engine writes Item+off from the record
#define GD_ITEM_LOAD "?Load@Item@GAME@@UEAAXAEBVLoadTable@2@@Z"

// Game.dll : log only: the call the reagent box makes for an explicit drop
#define GD_GAMEENGINE_ADDITEMTOREAGENTS "?AddItemToReagents@GameEngine@GAME@@QEAA_NI@Z"

// Game.dll : log only: the withdraw path
#define GD_GAMEENGINE_TAKEITEMFROMREAGENTS_NAME "?TakeItemFromReagents@GameEngine@GAME@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z"

// Game.dll : log only: the id overload of the withdraw path (tail-calls the string one)
#define GD_GAMEENGINE_TAKEITEMFROMREAGENTS_ID "?TakeItemFromReagents@GameEngine@GAME@@QEAAHIH@Z"

// Game.dll : THE authoritative count for one record - the engine's own map lookup
#define GD_GAMEENGINE_GETREAGENTITEMCOUNT "?GetReagentItemCount@GameEngine@GAME@@QEBAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$vector@I@mem@@@Z"

// Game.dll : READ ONLY - `lea rdx,[rcx+disp32]` gives the ItemReplicaInfo offset inside Item
#define GD_ITEM_GETITEMREPLICAINFO "?GetItemReplicaInfo@Item@GAME@@UEBAXAEAUItemReplicaInfo@2@@Z"

// Game.dll : READ ONLY: the member constructed right after the ItemReplicaInfo pins the block's size
#define GD_ITEM_CTOR "??0Item@GAME@@QEAA@XZ"

// Game.dll : READ ONLY - its 6 code bytes carry the seedRerolls field offset (Ascended state)
#define GD_ITEM_GETSEEDREROLLS "?GetSeedRerolls@Item@GAME@@QEBAIXZ"

// Game.dll : READ ONLY - its 6 code bytes carry the affixRerolls field offset
#define GD_ITEM_GETAFFIXREROLLS "?GetAffixRerolls@Item@GAME@@QEBAIXZ"

// Game.dll : READ ONLY - its 6 code bytes carry the prefix ItemClassification offset
#define GD_ITEM_GETPREFIXCLASSIFICATION "?GetPrefixClassification@Item@GAME@@QEBA?AW4ItemClassification@2@XZ"

// Game.dll : READ ONLY - its 6 code bytes carry the suffix ItemClassification offset
#define GD_ITEM_GETSUFFIXCLASSIFICATION "?GetSuffixClassification@Item@GAME@@QEBA?AW4ItemClassification@2@XZ"

// Game.dll : THE creation call, and the identity substitution point
#define GD_ITEM_CREATEITEM "?CreateItem@Item@GAME@@SAPEAV12@AEBUItemReplicaInfo@2@@Z"

// Game.dll : observed: a creation route of the reagent-box take (record -> item)
#define GD_CONTROLLERCHAR_CREATEITEMININVENTORY "?CreateItemInInventory@ControllerCharacter@GAME@@UEAAPEAVItem@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z"

// Game.dll : observed: the other creation route a take could use
#define GD_GAMEENGINE_CREATEITEMFORCHARACTER "?CreateItemForCharacter@GameEngine@GAME@@QEAAXIAEBVWorldCoords@2@AEAUItemReplicaInfo@2@PEAV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z"

// Game.dll : log only: the 4th AddItemToReagents caller (a drop the UI could not place)
#define GD_CURSORITEMMOVE_CANCEL "?Cancel@CursorHandlerItemMove@GAME@@UEAA_NXZ"

// Game.dll : `lea rax,[rcx+0x36D80]; ret` - THE reagent map, walked for the node
#define GD_GAMEENGINE_GETPLAYERREAGENTS "?GetPlayerReagents@GameEngine@GAME@@QEBAAEBV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@UReagentData@GAME@@@mem@@XZ"

// Game.dll : `mov eax,[rcx+0x88C]; ret` - the prototype's stack size == the box count
#define GD_ITEM_GETSTACKSIZE_R "?GetStackSize@Item@GAME@@UEBAIXZ"

// Game.dll : the only stack write the mod makes - `mov [rcx+0x88C],edx; mov [rcx+0x6B0],edx; ret`
#define GD_ITEM_SETSTACKSIZE "?SetStackSize@Item@GAME@@UEAAXI@Z"

// Game.dll : READ ONLY: its ADDRESS is the folded `xor al,al; ret` no-op stub (525 exports)
#define GD_ITEMEQUIPMENT_INCREMENTSTACK "?IncrementStack@ItemEquipment@GAME@@UEAA_NIAEAI@Z"

// Game.dll : READ ONLY: the real base implementation, for the log line only
#define GD_ITEM_INCREMENTSTACK "?IncrementStack@Item@GAME@@UEAA_NIAEAI@Z"

// Game.dll : auto-deposit button: our gate is disarmed while this is on the stack
#define GD_PLAYERINVCTRL_DEPOSITREAGENTS "?DepositReagents@PlayerInventoryCtrl@GAME@@QEAAXXZ"

// Game.dll : auto-deposit: same
#define GD_SACK_DEPOSITSACKINTOREAGENTS "?DepositSackIntoReagents@InventorySack@GAME@@QEAA_NPEAVControllerPlayer@2@@Z"

// Game.dll : auto-deposit: same
#define GD_GAMEENGINE_DEPOSITTRANSFERREAGENTS "?DepositTransferReagents@GameEngine@GAME@@QEAAXXZ"

// Game.dll : log: the explicit drop of the cursor item on a reagent box
#define GD_CURSORITEMMOVE_PRIMARYREAGENTACTIVATE "?PrimaryReagentActivate@CursorHandlerItemMove@GAME@@UEAA_NXZ"

// Game.dll : log: the shift-click / quick drop path into the reagent page
#define GD_CURSORITEMMOVE_QUICKDROPINREAGENTS "?QuickDropInReagents@CursorHandlerItemMove@GAME@@UEAA_NXZ"

// Game.dll : READ ONLY - its 7 code bytes carry the `soulbound` field offset (drop condition 1)
#define GD_ITEM_ISSOULBOUND "?IsSoulbound@Item@GAME@@QEBA?B_NXZ"

// Game.dll : READ ONLY - its 7 code bytes carry the `untradeable` field offset (drop condition 2)
#define GD_ITEM_ISUNTRADEABLE "?IsUntradeable@Item@GAME@@QEBA?B_NXZ"

// Engine.dll : keeps the item registry free of dangling pointers
#define GD_OBJECTMANAGER_DESTROYOBJECTEX "?DestroyObjectEx@ObjectManager@GAME@@QEAAXPEAVObject@2@PEBDH@Z"

// Engine.dll : liveness check before EVERY write into an Item
#define GD_OBJECTMANAGER_ISOBJECTONDELETEDLIST "?IsObjectOnDeletedList@ObjectManager@GAME@@QEAA_NPEAVObject@2@@Z"

// Engine.dll : the id-keyed half of the same liveness check
#define GD_OBJECTMANAGER_ISOBJECTIDONDELETEDLIST "?IsObjectIdOnDeletedList@ObjectManager@GAME@@QEAA_NI@Z"

// Engine.dll : the GameInfo the multiplayer flag lives on
#define GD_ENGINE_GETGAMEINFO "?GetGameInfo@Engine@GAME@@QEAAPEAVGameInfo@2@XZ"

// Engine.dll : THE session mode (GameInfo+0x1C0) - a gate only while mp_collect=0
#define GD_GAMEINFO_GETISMULTIPLAYER "?GetIsMultiPlayer@GameInfo@GAME@@QEBA_NXZ"

// Engine.dll : OPTIONAL telemetry only (GameInfo+0x1C1) - am I the host? Never a gate
#define GD_GAMEINFO_GETISSERVER "?GetIsServer@GameInfo@GAME@@QEBA_NXZ"

// Engine.dll : OPTIONAL telemetry only (GameInfo+0x1B8). lobby size vs live roster is unproven - never gate on it
#define GD_GAMEINFO_GETNUMOFPLAYERS "?GetNumOfPlayers@GameInfo@GAME@@QEBAIXZ"

// Engine.dll : OPTIONAL telemetry only (GameInfo+0x1CC) - the save-header game mode
#define GD_GAMEINFO_GETMODE "?GetMode@GameInfo@GAME@@QEBAIXZ"

// Engine.dll : THE collection mode - the loaded character's own hardcore flag. A const method returning bool. GameEngine+0x375BA is NOT this (it read 1 on softcore characters)
#define GD_GAMEINFO_GETHARDCORE "?GetHardcore@GameInfo@GAME@@QEBA_NXZ"

// Engine.dll : OPTIONAL telemetry only (Engine+0x6A8). 0 = the stub, i.e. commands execute LOCALLY; 1 = they round-trip. Never a gate
#define GD_ENGINE_ISNETWORKENABLED "?IsNetworkEnabled@Engine@GAME@@QEAA_NXZ"

// Engine.dll : OPTIONAL telemetry only (Engine+0x668 == +0x678). a host round-trips through its own loopback. Never a gate
#define GD_ENGINE_ISNETWORKSERVER "?IsNetworkServer@Engine@GAME@@QEAA_NXZ"

// Engine.dll : OPTIONAL telemetry only (Engine+0x668 == +0x670). Engine state, not lobby state. Never a gate
#define GD_ENGINE_ISNETWORKCLIENT "?IsNetworkClient@Engine@GAME@@QEAA_NXZ"

// Game.dll : world teardown - the item registry is cleared here
#define GD_GAMEENGINE_EXITPLAYINGMODE "?ExitPlayingMode@GameEngine@GAME@@QEAAXXZ"

// Engine.dll : post-detour: the moment every game .arz is loaded and the checksum is already taken
#define GD_ENGINE_LOADMAINDATABASE "?LoadMainDatabase@Engine@GAME@@AEAAXXZ"

// Engine.dll : called by us with the absolute path of uniq.arz
#define GD_ENGINE_LOADDATABASE "?LoadDatabase@Engine@GAME@@AEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z"

// Engine.dll : fallback route (takes DIRECTORIES, not files)
#define GD_ENGINE_LOADADDITIONALDATABASES "?LoadAdditionalDatabases@Engine@GAME@@QEAAXAEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@mem@@@Z"

// Engine.dll : 0 until LoadMainDatabase finishes: the late-load fallback polls it
#define GD_ENGINE_GETDATABASEARCHIVECHECKSUM "?GetDatabaseArchiveChecksum@Engine@GAME@@QEAAIXZ"

// Engine.dll : must stay false: proves we did not go through InitializeMod
#define GD_ENGINE_HASLOADEDCUSTOMDATABASE "?HasLoadedCustomDatabase@Engine@GAME@@QEBA_NXZ"

// Engine.dll : verification: the ObjectManager singleton
#define GD_SINGLETON_OBJECTMANAGER_GET "?Get@?$Singleton@VObjectManager@GAME@@@GAME@@SAPEAVObjectManager@2@XZ"

// Engine.dll : DETOURED - the exe asks it for the reagent page record; we substitute the path
#define GD_OBJECTMANAGER_LOADTABLEFILE "?LoadTableFile@ObjectManager@GAME@@QEAAPEBVLoadTable@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z"

// Engine.dll : DETOURED - the other half of the pair ReagentWindow::Load calls
#define GD_OBJECTMANAGER_GETLOADTABLE "?GetLoadTable@ObjectManager@GAME@@QEBAAEBVLoadTable@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z"

// Engine.dll : verification: how many entries the record's reagentBoxes array has
#define GD_LOADTABLEBINARY_GETNUMELEMENTSFORFIELD "?GetNumElementsForField@LoadTableBinary@GAME@@UEBAIPEBD@Z"

// Game.dll : rescue: step 1 of the exe take - who receives the item
#define GD_GAMEENGINE_GETMAINPLAYER "?GetMainPlayer@GameEngine@GAME@@QEBAPEAVPlayer@2@XZ"

// Game.dll : rescue: Player vtable +0x938 - the exe's room check before it creates anything
#define GD_PLAYER_ISINVENTORYSPACEAVAILABLE "?IsInventorySpaceAvailable@Player@GAME@@UEBA_NPEBVItem@2@@Z"

// Game.dll : rescue: what the exe does when the room check fails
#define GD_PLAYER_PLAYINVENTORYFULLSOUND "?PlayInventoryFullSound@Player@GAME@@QEAAXXZ"

// Game.dll : rescue: the clamp the exe applies to the count it takes
#define GD_GAMEENGINE_GETITEMMAXSTACKSIZE "?GetItemMaxStackSize@GameEngine@GAME@@QEBAIXZ"

// Game.dll : rescue: the controller that owns the receiving inventory
#define GD_CHARACTER_GETCONTROLLERID "?GetControllerId@Character@GAME@@QEBA?BIXZ"

// Game.dll : rescue: THE placement call - the exe take's only inventory write
#define GD_CONTROLLERCHAR_SENDADDITEMTOINVENTORY "?SendAddItemToInventory@ControllerCharacter@GAME@@QEAAXI@Z"

// Game.dll : rescue: Player vtable +0x578, called right after the placement
#define GD_PLAYER_GIVEITEMTOCHARACTER "?GiveItemToCharacter@Player@GAME@@UEAAXPEAVItem@2@_N1@Z"

// Game.dll : rescue: Item vtable +0x410, the last call of the exe take
#define GD_ITEM_PLAYDROPSOUND "?PlayDropSound@Item@GAME@@UEAAXXZ"

// Game.dll : rescue FALLBACK: the transfer stash, used when the inventory is full
#define GD_GAMEENGINE_ADDITEMTOTRANSFER "?AddItemToTransfer@GameEngine@GAME@@QEAA_NII_N@Z"

// Game.dll : rescue FALLBACK: read only - the sack-level room test
#define GD_SACK_ISSPACEFORITEM "?IsSpaceForItem@InventorySack@GAME@@QEBA_NPEBVItem@2@_N@Z"

// Game.dll : READ ONLY: cross-check that slots 0x410/0x590/0x610/0x618 are the exports above
#define GD_ITEM_VFTABLE_OBJECT "??_7Item@GAME@@6BObject@1@@"

// Game.dll : READ ONLY: cross-check that slots 0x578/0x938 are the two Player exports above
#define GD_PLAYER_VFTABLE_OBJECT "??_7Player@GAME@@6BObject@1@@"

// Engine.dll : verification: only call the Binary accessor when the object really is one
#define GD_LOADTABLEBINARY_VFTABLE "??_7LoadTableBinary@GAME@@6B@"

// Game.dll : THE box-badge repaint - called after every live relayout
#define GD_GAMEENGINE_SYNCCARAVANREAGENTS "?SyncCaravanReagents@GameEngine@GAME@@QEAAXXZ"

// Game.dll : THE load bracket - every stored prototype is created inside it
#define GD_GAMEENGINE_READPLAYERREAGENTS "?ReadPlayerReagents@GameEngine@GAME@@QEAA_NAEAVCheckedReader@2@@Z"

// Game.dll : half of MENU READY / CHARACTER LOADED
#define GD_GAMEENGINE_ISGAMELOADING "?IsGameLoading@GameEngine@GAME@@QEBA_NXZ"

// Game.dll : READ ONLY - `lea rax,[rcx+disp32]` gives the name std::wstring offset
#define GD_PLAYER_GETPLAYERNAME "?GetPlayerName@Player@GAME@@QEBAPEBGXZ"

// Game.dll : static - how many inventory sacks this install has
#define GD_PLAYER_GETMAXIMUMSACKS "?GetMaximumSacks@Player@GAME@@SAIXZ"

// Game.dll : one inventory sack (NULL entries are normal)
#define GD_PLAYER_GETSACK "?GetSack@Player@GAME@@QEAAPEAVInventorySack@2@H@Z"

// Game.dll : mem::map<u32 objectId, Rect> - every item id in that sack
#define GD_SACK_GETINVENTORY_CONST "?GetInventory@InventorySack@GAME@@QEBAAEBV?$map@IVRect@GAME@@@mem@@XZ"

// Game.dll : exe site A 0x1EAB4E - step 2 of the deposit, ONLY on AddItem true
#define GD_PLAYERINVCTRL_REMOVEITEM "?RemoveItem@PlayerInventoryCtrl@GAME@@QEAA_NI_N@Z"

// Game.dll : exe site A 0x1EAB5D - step 3 of the deposit
#define GD_CONTROLLERCHAR_SENDREMOVEITEMFROMINVENTORY "?SendRemoveItemFromInventory@ControllerCharacter@GAME@@QEAAXI@Z"

// Game.dll : `lea rax,[rcx+0x470]` - the RemoveItem `this`, never open-coded
#define GD_CONTROLLERPLAYER_GETINVENTORYCTRL "?GetInventoryCtrl@ControllerPlayer@GAME@@QEAAAEAVPlayerInventoryCtrl@2@XZ"

// Game.dll : READ ONLY - its bytes carry Player+0x16C0, the ControllerPlayer id
#define GD_CURSORHANDLER_GETPLAYERCTRL "?GetPlayerCtrl@CursorHandler@GAME@@IEAAPEAVControllerPlayer@2@XZ"

// Game.dll : READ ONLY 0x3DAA10 `([rcx+0x28]-[rcx+0x20])>>3` - how many bags the PlayerInventoryCtrl RemoveItem searches
#define GD_PLAYERINVCTRL_GETNUMBEROFSACKS "?GetNumberOfSacks@PlayerInventoryCtrl@GAME@@QEBAIXZ"

// Game.dll : READ ONLY 0x3DA770 `[[rcx+0x20]+rdx*8]` - one of those bags (no bounds check: clamp with GetNumberOfSacks)
#define GD_PLAYERINVCTRL_GETSACK "?GetSack@PlayerInventoryCtrl@GAME@@QEAAPEAVInventorySack@2@H@Z"

// Game.dll : READ ONLY 0x30BBD0 - the same sack+0x20 map and the same node+0x1C key PlayerInventoryCtrl::RemoveItem walks, so it answers 'will the caller's removal find it'
#define GD_SACK_CONTAINSITEM_ID "?ContainsItem@InventorySack@GAME@@QEBA_NI@Z"

// Game.dll : `mov byte [rcx+0x35],dl; ret` - off for the run, restored on every exit
#define GD_GAMEENGINE_SETAUTOSAVE "?SetAutoSave@GameEngine@GAME@@QEAAX_N@Z"

// Game.dll : the matching getter, so the step can assert what it did
#define GD_GAMEENGINE_GETAUTOSAVE "?GetAutoSave@GameEngine@GAME@@QEBA_NXZ"

// Game.dll : THE tooltip assembly (0x3118A0, Item vtable +0x458). ItemEquipment calls it with a plain rel32 at 0x3299AF, so one detour covers the whole equipment collection
#define GD_ITEM_GETUIDISPLAYTEXT "?GetUIDisplayText@Item@GAME@@UEBAXPEBVCharacter@2@AEAV?$vector@UGameTextLine@GAME@@@mem@@_N@Z"

// Game.dll : it CALLS the base (0x3299AF) and then appends its own lines, so the latch taken inside the base sees a PARTIAL vector - hooking the override too is what makes the line count an exact fingerprint for the whole equipment collection
#define GD_ITEMEQUIPMENT_GETUIDISPLAYTEXT "?GetUIDisplayText@ItemEquipment@GAME@@UEBAXPEBVCharacter@2@AEAV?$vector@UGameTextLine@GAME@@@mem@@_N@Z"

// Game.dll : relics are ItemArtifact in this collection and the override does NOT call the base, so it needs its own detour
#define GD_ITEMARTIFACT_GETUIDISPLAYTEXT "?GetUIDisplayText@ItemArtifact@GAME@@UEBAXPEBVCharacter@2@AEAV?$vector@UGameTextLine@GAME@@@mem@@_N@Z"

// Game.dll : the other override that does not call the base - cheap, so it is covered too
#define GD_ITEMRELIC_GETUIDISPLAYTEXT "?GetUIDisplayText@ItemRelic@GAME@@UEBAXPEBVCharacter@2@AEAV?$vector@UGameTextLine@GAME@@@mem@@_N@Z"

// Game.dll : THE layout entry point (0x302A90). Reads the vector at [+0] and [+8] only and writes nothing, which is what makes a borrowed N+1 array safe
#define GD_GAMETEXTLINETOSTRING "?GameTextLineToString@GAME@@YAXAEBV?$vector@UGameTextLine@GAME@@@mem@@AEAV?$list@UGameTextString@GAME@@@3@@Z"

// Game.dll : the wide-string GameTextLine constructor (0x2FEC10) - called ONCE per process per state, so the mod never hand-builds an engine struct
#define GD_GAMETEXTLINE_CTOR_W "??0GameTextLine@GAME@@QEAA@W4GameTextClass@1@AEBV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@_NPEBVGraphicsTexture@1@M@Z"
